const common = {
  brand: { badge: 'Selo Prively', name: 'Prively', tagline: 'O teu Privê digital.', discreet: 'Menos público, muito mais Privê.' },
  levels: { Bronze: 'Bronze', Prata: 'Prata', Ouro: 'Ouro', VIP: 'VIP' },
  nav: { enter: 'Entrar no Privê', creator: 'Sê criadora', home: 'Início', designSystem: 'Sistema de design' },
  hero: { title: 'O teu Privê digital.', body: 'Um espaço privado para conteúdo, ligação e controlo, pensado para adultos.', privacyTitle: 'Discrição por desenho.', privacyBody: 'Identidade social separada dos dados legais, notificações neutras e um produto construído com regras claras.', clientAction: 'Entrar no Privê', creatorAction: 'Sê criadora' },
  ageGate: { eyebrow: 'Antes de entrar', title: 'Confirma que tens 18 anos ou mais.', body: 'Esta confirmação é o primeiro portão. A verificação de identidade acontece depois.', confirm: 'Tenho 18 anos ou mais', leave: 'Sair', policy: 'Ao continuar, aceitas consultar os Termos e a Política de Privacidade.' },
  auth: { signInTitle: 'Entrar no Privê', signUpTitle: 'Criar conta', creatorSignInTitle: 'Entrar como criadora', creatorSignUpTitle: 'Criar conta de criadora', adminTitle: 'Administração Prively', adminEyebrow: 'Área restrita', email: 'Email', password: 'Palavra-passe', handle: 'Pseudónimo', signIn: 'Entrar', signUp: 'Criar conta', noAccount: 'Ainda não tens conta?', haveAccount: 'Já tens conta?', createNow: 'Criar agora', signInNow: 'Entrar agora', back: 'Voltar', invalidCredentials: 'O email ou a palavra-passe não estão correctos.', invalidHandle: 'Escolhe um pseudónimo válido.', genericError: 'Não foi possível concluir esta acção. Tenta novamente.', adminRequired: 'Esta conta não tem permissões de administração.', adminUsePortal: 'As contas de administração entram pela área /admin.', creatorRequired: 'Esta conta não está configurada como criadora.', creatorUsePortal: 'As contas de criadora devem entrar pela área de criadora.', registrationNoSession: 'A conta foi criada, mas a sessão não pôde ser iniciada.', clientRegistered: 'Conta de cliente criada.', ageConfirmed: 'Confirmo que tenho 18 anos ou mais.', termsAccepted: 'Li e aceito os Termos e Condições.', privacyAccepted: 'Li e aceito a Política de Privacidade.', acceptanceRequired: 'Confirme os requisitos para criar a conta.', legalAcceptanceError: 'Não foi possível registar as aceitações legais. A conta não foi activada.', creatorRegistered: 'Conta de criadora criada.' },
  admin: { title: 'Prively Control Room', description: 'Centro de controlo da Prively. O acesso é verificado no servidor e cada área respeita as permissões administrativas.', open: 'Abrir área', areas: { users: 'Utilizadores', kyc: 'Verificação de identidade', moderation: 'Moderação', finance: 'Financeiro', compliance: 'Conformidade', audit: 'Auditoria', archive: 'Arquivo', legalHolds: 'Retenções legais', config: 'Configuração', featureFlags: 'Funcionalidades', commissions: 'Comissões', badges: 'Selos', gifts: 'Presentes', safePlaces: 'Locais seguros', support: 'Suporte', tickets: 'Tickets', emergencies: 'Emergências', reports: 'Relatórios' } },
admin: { title: 'Prively Control Room', description: 'Centro de controlo da Prively. O acesso é verificado no servidor e cada área respeita as permissões administrativas.', open: 'Abrir área', areas: { users: 'Utilizadores', kyc: 'Verificação de identidade', moderation: 'Moderação', finance: 'Financeiro', compliance: 'Conformidade', audit: 'Auditoria', archive: 'Arquivo', legalHolds: 'Retenções legais', config: 'Configuração', featureFlags: 'Funcionalidades', commissions: 'Comissões', badges: 'Selos', gifts: 'Presentes', safePlaces: 'Locais seguros', support: 'Suporte', tickets: 'Tickets', emergencies: 'Emergências', reports: 'Relatórios' } },admin: { title: 'Prively Control Room', description: 'Centro de controlo da Prively. O acesso é verificado no servidor e cada área respeita as permissões administrativas.', open: 'Abrir área', areas: { users: 'Utilizadores', kyc: 'Verificação de identidade', moderation: 'Moderação', finance: 'Financeiro', compliance: 'Conformidade', audit: 'Auditoria', archive: 'Arquivo', legalHolds: 'Retenções legais', config: 'Configuração', featureFlags: 'Funcionalidades', commissions: 'Comissões', badges: 'Selos', gifts: 'Presentes', safePlaces: 'Locais seguros', support: 'Suporte', tickets: 'Tickets', emergencies: 'Emergências', reports: 'Relatórios' } }, sampleSans: 'Privê em controlo.', sampleSerif: 'O teu Privê.', title: 'Prively Interface Kernel', intro: 'Inventário vivo do sistema de design. Estes componentes são a base reutilizável do produto.', foundations: 'Fundamentos', components: 'Componentes', states: 'Estados', typography: 'Tipografia', colors: 'Cor', buttons: 'Botões', levels: 'Níveis', money: 'Dinheiro', cortina: 'Cortina', cordao: 'Cordão', shield: 'Escudo de privacidade', empty: 'Estado vazio', pin: 'PinPad' },
  common: { primary: 'Acção principal', secondary: 'Acção secundária', loading: 'A carregar', error: 'Erro', empty: 'Vazio', success: 'Concluído', close: 'Fechar', language: 'Idioma' },
  privacy: { notice: 'As tuas conversas são privadas. Ficam protegidas com cifragem em trânsito e em repouso, e no dia-a-dia só as pessoas na conversa as vêem.', learnMore: 'Saber mais' },
  curtain: { unlock: 'Desbloquear por {{price}}', protected: 'Protegido por Cortina', unlocked: 'Conteúdo desbloqueado', pin: 'PIN', delete: 'Apagar', confirm: 'OK' },
  errors: { ageRequired: 'É necessário confirmar a idade para continuar.' },
  experience: {
    workspace: { client: 'Privê do cliente', creator: 'Estúdio da criadora' },
    nav: { discover: 'Descobrir', feed: 'Feed', wallet: 'Carteira', messages: 'Mensagens', account: 'Eu', studio: 'Estúdio', content: 'Conteúdo', create: 'Criar', settings: 'Definições' },
    session: { connected: 'Ligação disponível', unconfigured: 'Supabase não configurado', active: 'Sessão activa', account: 'Conta autenticada', preview: 'Sem sessão', devOnly: 'pré-visualização de desenvolvimento' },
    pages: {
      emptyAction: 'Os dados reais desta área serão ligados através do backend da respectiva funcionalidade.',
      discover: { title: 'Descobrir', intro: 'Explorar criadoras', detail: 'A descoberta será alimentada por perfis, localização aproximada, filtros e disponibilidade reais. Nesta fase não existem resultados inventados.' },
      feed: { title: 'Feed', intro: 'Conteúdo', detail: 'O feed vertical será ligado ao catálogo real e às regras de visibilidade do servidor. Nenhum conteúdo fictício é apresentado.' },
      profile: { title: 'Perfil', intro: 'Canal', detail: 'O perfil será carregado pelo handle através do backend. A autorização de conteúdo continuará a ser decidida no servidor.' },
      post: { title: 'Publicação', intro: 'Conteúdo', detail: 'A publicação será carregada pelo identificador real e só exibirá media quando a autorização correspondente existir.' },
      messages: { title: 'Mensagens', intro: 'Conversas privadas', detail: 'A caixa de entrada será ligada ao Realtime e às regras de bloqueio, visibilidade e mensagens pagas no backend.' },
      message: { title: 'Conversa', intro: 'Mensagens privadas', detail: 'A conversa só será carregada quando existir uma relação de membros autorizada.' },
      wallet: { title: 'Carteira', intro: 'Saldo interno', balanceUnavailable: 'Saldo ainda não ligado', notice: 'Os movimentos financeiros serão sempre calculados no servidor e registados no livro-razão.', empty: 'Sem movimentos financeiros para apresentar', detail: 'A carteira permanece sem dados até existir a fonte financeira real.' },
      purchases: { title: 'Compras', intro: 'Histórico', detail: 'O histórico será derivado das transacções reais do utilizador. Não são criadas compras de demonstração.' },
      wishlist: { title: 'Lista de desejos', intro: 'Guardar para depois', detail: 'Os itens serão persistidos na base de dados e carregados apenas para o utilizador autenticado.' },
      account: { title: 'Conta', intro: 'Identidade da conta', detail: 'Esta área trata dados de conta não sensíveis. A identidade social continua separada da identidade legal.' },
      privacy: { title: 'Privacidade', intro: 'Controlo e discrição', detail: 'As regras de privacidade serão persistidas e aplicadas no servidor quando o respectivo backend estiver activo.' },
      limits: { title: 'Limites de gasto', intro: 'Controlo financeiro', detail: 'Os limites terão efeito no servidor através de regras de gasto. A interface não pode substituir essa autoridade.' },
      discreet: { title: 'Modo discreto', intro: 'Protecção no dispositivo', detail: 'A superfície desta área está definida; a persistência segura e o comportamento completo serão ligados com o backend de privacidade.' },
      creator: {
        studio: { title: 'Estúdio', intro: 'Operação da criadora', detail: 'O painel de estúdio será alimentado por ganhos, conteúdo, fãs e actividade reais, sem métricas inventadas.' },
        content: { title: 'Conteúdo', intro: 'Publicação e catálogo', detail: 'Esta área será ligada ao pipeline de upload, consentimento, moderação e publicação do backend.' },
        store: { title: 'Loja', intro: 'Produtos e packs', detail: 'Produtos, packs e encomendas serão lidos da base de dados e processados com as regras financeiras reais.' },
        agenda: { title: 'Agenda', intro: 'Disponibilidade social', detail: 'A agenda será baseada em janelas reais e locais públicos aprovados pela equipa.' },
        fans: { title: 'Fãs', intro: 'Relações e gestão', detail: 'A gestão de fãs será derivada de relações reais e identificada por pseudónimo quando aplicável.' },
        earnings: { title: 'Ganhos', intro: 'Financeiro da criadora', detail: 'Ganhos pendentes e disponíveis só aparecem a partir do ledger e das regras reais de libertação.' },
        analytics: { title: 'Analítica', intro: 'Resultados', detail: 'Os gráficos desta área só serão preenchidos quando existirem agregações reais.' },
        requests: { title: 'Pedidos', intro: 'Pedidos personalizados', detail: 'Pedidos e escrow serão ligados ao motor financeiro quando essa camada estiver implementada.' },
        auctions: { title: 'Leilões', intro: 'Conteúdo em leilão', detail: 'Os leilões dependerão de bloqueios de concorrência e escrow no servidor.' },
        lives: { title: 'Lives e chamadas', intro: 'Ao vivo', detail: 'As salas e a cobrança por minuto serão criadas somente através do backend e do fornecedor real.' },
        settings: { title: 'Definições do estúdio', intro: 'Configuração', detail: 'As configurações serão ligadas a dados persistidos e permissões reais da criadora.' }
      },
      seCreator: { title: 'Sê criadora', intro: 'Entrada para criadoras', detail: 'O processo de entrada parte do registo e segue para verificação de identidade antes de qualquer publicação.', action: 'Criar conta' },
      about: { title: 'Sobre a Prively', intro: 'A plataforma', detail: 'Informação institucional e de produto da Prively.' },
      help: { title: 'Ajuda', intro: 'Centro de ajuda', detail: 'Orientação sobre conta, privacidade, segurança e uso da plataforma.' },
      legal: {
        termos: { title: 'Termos', intro: 'Documento legal', detail: 'A versão publicada dos termos deverá ser ligada ao conteúdo legal aprovado antes do lançamento.' },
        privacidade: { title: 'Privacidade', intro: 'Documento legal', detail: 'A política publicada deverá reflectir os dados efectivamente tratados pela plataforma.' },
        'conteudo-proibido': { title: 'Conteúdo proibido', intro: 'Documento legal', detail: 'As regras publicadas devem corresponder aos mecanismos de moderação efectivamente activos.' },
        reembolsos: { title: 'Reembolsos', intro: 'Documento legal', detail: 'A política deve corresponder às regras reais de pagamentos, disputas e reembolsos.' },
        cookies: { title: 'Cookies', intro: 'Documento legal', detail: 'A política deve corresponder aos mecanismos reais de armazenamento e análise.' },
        dmca: { title: 'Remoção de conteúdo', intro: 'Documento legal', detail: 'O processo de remoção será ligado à fila real de conformidade e moderação.' }
      },
      info: { note: 'Conteúdo legal e institucional só deve ser publicado depois de validado e versionado.' }
    }
  },
  surface: {
    title: 'Área da Prively',
    intro: 'Esta superfície já está estruturada no código e segue o sistema visual, routing e estados da plataforma.',
    backendGated: 'A capacidade operacional correspondente só é apresentada em produção quando o backend real, permissões e integrações estiverem activos.',
    route: 'Rota',
    stateTitle: 'Estado operacional',
    stateIntro: 'Superfície preparada para estados extremos, falhas e controlo de acesso.',
    stateDetail: 'O estado é representado como uma superfície real da aplicação, sem dados simulados.',
    state: 'Estado',
    stateBackend: 'Este estado deve ser ligado ao fluxo real que o produziu antes de ser exposto como experiência de produção.'
  },
  phase3Advanced: {support:{eyebrow:"Apoio",title:"Apoiar a criadora",intro:"Subscrições, gorjetas e presentes com cobrança autorizada pelo servidor.",missingChannel:"Canal em falta",missingChannelBody:"Abra esta área a partir de um canal real.",tipTitle:"Gorjeta",amount:"Valor em MT",message:"Mensagem opcional",sendTip:"Enviar gorjeta",giftsTitle:"Presentes",sendGift:"Enviar",noGifts:"Sem presentes configurados",noGiftsBody:"O catálogo de presentes ainda não foi configurado.",subscriptionsTitle:"Subscrições",months:"{{count}} mês(es)",noTiers:"Sem níveis",noTiersBody:"Este canal ainda não tem níveis de subscrição configurados."},bundles:{eyebrow:"Bundles",clientTitle:"Packs de conteúdo",clientIntro:"Packs persistidos e comprados através do ledger.",buy:"Comprar pack",emptyTitle:"Sem packs",emptyBody:"Ainda não existem packs reais.",creatorTitle:"Packs da criadora",creatorIntro:"Agrupe publicações reais num pack com preço único.",name:"Nome do pack",price:"Preço em MT",description:"Descrição",create:"Criar pack"},engagement:{eyebrow:"Interacção",creatorTitle:"Sorteios e enquetes",creatorIntro:"Crie interacções reais para a sua comunidade.",clientTitle:"Participação",clientIntro:"Vote e participe em interacções abertas.",pollTitle:"Nova enquete",question:"Pergunta",optionsHint:"Uma opção por linha",createPoll:"Criar enquete",giveawayTitle:"Novo sorteio",title:"Título",winnerCountLabel:"Número de vencedores",createGiveaway:"Criar sorteio",winnerCount:"{{count}} vencedor(es)",enter:"Participar",emptyTitle:"Sem actividades",emptyBody:"Ainda não há enquetes ou sorteios activos."},schedule:{eyebrow:"Agenda",title:"Disponibilidade",intro:"Defina janelas reais de disponibilidade.",area:"Área pública opcional",create:"Criar janela"},rankings:{eyebrow:"Rankings",title:"Rankings semanais",intro:"Classificações calculadas pelo backend.",creators:"Criadoras",fans:"Fãs"}}
} as const;

export default common;