import { useEffect, useState } from 'react';
import { ShieldCheck, ArrowLeft } from '@phosphor-icons/react';
import { useNavigate, Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Ficha } from '@/design/Ficha';
import { Botao } from '@/design/Botao';
import { requireSupabase } from '@/lib/supabase';

export function AdminMfaPage(){
 const {t}=useTranslation(); const navigate=useNavigate(); const [factorId,setFactorId]=useState<string|null>(null); const [qr,setQr]=useState<string|null>(null); const [secret,setSecret]=useState<string|null>(null); const [code,setCode]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{void requireSupabase().auth.mfa.listFactors().then(({data,error})=>{if(error){setError(error.message);return;}const factor=data.totp.find((f)=>f.status==='verified');if(factor)setFactorId(factor.id);});},[]);
 const enroll=async()=>{setError(null);setLoading(true);const result=await requireSupabase().auth.mfa.enroll({factorType:'totp',friendlyName:'Prively Admin'});setLoading(false);if(result.error){setError(result.error.message);return;}setFactorId(result.data.id);setQr(result.data.totp.qr_code);setSecret(result.data.totp.secret);};
 const verify=async()=>{if(!factorId)return;setError(null);setLoading(true);const sb=requireSupabase();const challenge=await sb.auth.mfa.challenge({factorId});if(challenge.error){setLoading(false);setError(challenge.error.message);return;}const result=await sb.auth.mfa.verify({factorId,challengeId:challenge.data.id,code});setLoading(false);if(result.error){setError(result.error.message);return;}await sb.auth.refreshSession();navigate('/admin',{replace:true});};
 return <section className="mx-auto flex min-h-[calc(100vh-4rem)] max-w-xl items-center px-5 py-12 md:px-8"><Ficha variant="focus" className="w-full p-7 md:p-10"><Link to="/admin" className="inline-flex items-center gap-2 text-sm text-bone-500 no-underline"><ArrowLeft size={16}/>{t('auth.back')}</Link><div className="mt-8 flex items-center gap-3 text-bone-500"><ShieldCheck size={20}/>{t('adminMfa.eyebrow')}</div><h1 className="mt-4 font-display text-5xl leading-none text-bone-50">{t('adminMfa.title')}</h1><p className="mt-5 text-sm leading-6 text-bone-300">{t('adminMfa.body')}</p>{factorId&&!qr?<div className="mt-8 rounded-md border border-ok/30 bg-ok/5 p-4 text-sm text-bone-50">{t('adminMfa.alreadyEnabled')}<Botao className="mt-4" onClick={()=>navigate('/admin')}>{t('adminMfa.enter')}</Botao></div>:null}{!factorId?<Botao className="mt-8" onClick={()=>void enroll()} loading={loading}>{t('adminMfa.start')}</Botao>:null}{qr?<div className="mt-8 space-y-5"><img src={qr} alt={t('adminMfa.qrAlt')} className="mx-auto h-52 w-52 rounded bg-white p-2"/><p className="text-sm text-bone-300">{t('adminMfa.secret')}: <code className="text-bone-50">{secret}</code></p><input value={code} onChange={(e)=>setCode(e.target.value.replace(/\D/g,'').slice(0,8))} inputMode="numeric" placeholder={t('adminMfa.code')} className="min-h-12 w-full rounded-md border border-input bg-ink-850 px-3 text-bone-50 outline-none"/><Botao onClick={()=>void verify()} loading={loading} className="w-full">{t('adminMfa.verify')}</Botao></div>:null}{error?<p role="alert" className="mt-5 rounded-md border border-danger/35 bg-danger/5 p-3 text-sm text-bone-50">{error}</p>:null}</Ficha></section>;
}
