import { useEffect, useState, type FormEvent } from 'react';
import { CalendarBlank, Gift, Heart, Package, Poll, Trophy, UsersThree } from '@phosphor-icons/react';
import { useTranslation } from 'react-i18next';
import { useSearchParams } from 'react-router-dom';
import { Botao } from '@/design/Botao';
import { Ficha } from '@/design/Ficha';
import { EstadoVazio } from '@/design/EstadoVazio';
import { PageFrame } from '@/pages/PageFrame';
import { formatMznFromCents } from '@/lib/money';
import { supabase } from '@/lib/supabase';
import { phase3Rows, phase3Rpc } from '@/lib/phase3Api';

type Channel = { id: string; display_name: string };
type Tier = { id: string; channel_id: string; name: string; rank: number; price_month: number };
type GiftRow = { id: string; name: string; price: number; active: boolean };
type Bundle = { id: string; channel_id: string; name: string; description: string | null; price: number; status: string };
type Slot = { id: string; channel_id: string; starts_at: string; ends_at: string; area_label: string | null };
type Poll = { id: string; channel_id: string; question: string; closes_at: string | null; status: string };
type PollOption = { id: string; poll_id: string; label: string; sort_order: number };
type Giveaway = { id: string; channel_id: string; title: string; winner_count: number; starts_at: string; ends_at: string; status: string };
type Ranking = { rank: number; score: number; channel_id?: string; user_id?: string };

function ErrorMessage({ error }: { error: string | null }) {
  const { t } = useTranslation();
  return error ? <p role="alert" className="mt-4 text-sm text-danger">{t('phase3.errors.generic')}</p> : null;
}

export function ClientSupportCreatorPage() {
  const { t } = useTranslation();
  const [params] = useSearchParams();
  const channelId = params.get('channel') ?? '';
  const [tiers, setTiers] = useState<Tier[]>([]);
  const [gifts, setGifts] = useState<GiftRow[]>([]);
  const [tip, setTip] = useState('');
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => {
    if (!supabase || !channelId) return;
    void Promise.all([
      phase3Rows<Tier>(supabase, 'subscription_tiers', 'id,channel_id,name,rank,price_month'),
      phase3Rows<GiftRow>(supabase, 'gifts_catalog', 'id,name,price,active')
    ]).then(([a, b]) => { setTiers(a.filter((x) => x.channel_id === channelId)); setGifts(b.filter((x) => x.active)); })
      .catch((e: unknown) => setError(e instanceof Error ? e.message : 'load_error'));
  }, [channelId]);
  const subscribe = async (tier: Tier, period: number) => { setBusy(true); setError(null); try { await phase3Rpc('subscribe', { _tier: tier.id, _period: period, _idem: crypto.randomUUID() }); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'subscribe_error'); } finally { setBusy(false); } };
  const sendTip = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(null); try { await phase3Rpc('send_tip', { _channel: channelId, _amount: Math.round(Number(tip) * 100), _message: message, _idem: crypto.randomUUID() }); setTip(''); setMessage(''); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'tip_error'); } finally { setBusy(false); } };
  const sendGift = async (gift: GiftRow) => { setBusy(true); setError(null); try { await phase3Rpc('send_gift', { _channel: channelId, _gift: gift.id, _quantity: 1, _message: message, _idem: crypto.randomUUID() }); setMessage(''); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'gift_error'); } finally { setBusy(false); } };
  if (!supabase) return <PageFrame eyebrow={t('phase3.support.eyebrow')} title={t('phase3.support.title')} intro={t('phase3.support.intro')}><EstadoVazio title={t('phase3.backend.title')} body={t('phase3.backend.notConfigured')} /></PageFrame>;
  if (!channelId) return <PageFrame eyebrow={t('phase3.support.eyebrow')} title={t('phase3.support.title')} intro={t('phase3.support.intro')}><EstadoVazio title={t('phase3.support.missingChannel')} body={t('phase3.support.missingChannelBody')} /></PageFrame>;
  return <PageFrame eyebrow={t('phase3.support.eyebrow')} title={t('phase3.support.title')} intro={t('phase3.support.intro')}><ErrorMessage error={error}/><div className="grid gap-4 lg:grid-cols-2"><Ficha><div className="flex items-center gap-3"><Heart size={22}/><h2 className="text-lg text-bone-50">{t('phase3.support.tipTitle')}</h2></div><form onSubmit={sendTip} className="mt-5 space-y-4"><input value={tip} onChange={(e)=>setTip(e.target.value)} required min="1" inputMode="decimal" placeholder={t('phase3.support.amount')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><input value={message} onChange={(e)=>setMessage(e.target.value)} maxLength={500} placeholder={t('phase3.support.message')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><Botao type="submit" loading={busy}>{t('phase3.support.sendTip')}</Botao></form></Ficha><Ficha><div className="flex items-center gap-3"><Gift size={22}/><h2 className="text-lg text-bone-50">{t('phase3.support.giftsTitle')}</h2></div><div className="mt-5 grid gap-3">{gifts.map((gift)=><div key={gift.id} className="flex items-center justify-between gap-4 rounded-md border border-bone-50/8 p-3"><div><p className="text-bone-50">{gift.name}</p><p className="text-sm text-bone-400">{formatMznFromCents(gift.price)}</p></div><Botao type="button" disabled={busy} onClick={()=>void sendGift(gift)}>{t('phase3.support.sendGift')}</Botao></div>)}{!gifts.length?<EstadoVazio title={t('phase3.support.noGifts')} body={t('phase3.support.noGiftsBody')}/>:null}</div></Ficha></div><Ficha className="mt-6"><div className="flex items-center gap-3"><UsersThree size={22}/><h2 className="text-lg text-bone-50">{t('phase3.support.subscriptionsTitle')}</h2></div><div className="mt-5 grid gap-4 md:grid-cols-2">{tiers.map((tier)=><div key={tier.id} className="rounded-md border border-bone-50/8 p-4"><p className="text-bone-50">{tier.name}</p><p className="mt-2 font-display text-2xl text-bone-50">{formatMznFromCents(tier.price_month)}</p><div className="mt-4 flex flex-wrap gap-2">{[1,3,6,12].map((period)=><Botao key={period} type="button" disabled={busy} onClick={()=>void subscribe(tier,period)}>{t('phase3.support.months',{count:period})}</Botao>)}</div></div>)}{!tiers.length?<EstadoVazio title={t('phase3.support.noTiers')} body={t('phase3.support.noTiersBody')}/>:null}</div></Ficha></PageFrame>;
}

export function ClientBundlesPage() {
  const { t } = useTranslation();
  const [items, setItems] = useState<Bundle[]>([]); const [error, setError] = useState<string | null>(null);
  const load = async () => { if (!supabase) return; try { setItems(await phase3Rows<Bundle>(supabase, 'bundles', 'id,channel_id,name,description,price,status')); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'bundle_error'); } };
  useEffect(() => { void load(); }, []);
  const buy = async (id: string) => { try { await phase3Rpc('buy_bundle', { _bundle: id, _idem: crypto.randomUUID() }); await load(); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'bundle_buy_error'); } };
  return <PageFrame eyebrow={t('phase3.bundles.eyebrow')} title={t('phase3.bundles.clientTitle')} intro={t('phase3.bundles.clientIntro')}><ErrorMessage error={error}/><div className="grid gap-4 md:grid-cols-2">{items.filter((x)=>x.status==='active').map((item)=><Ficha key={item.id}><Package size={22}/><p className="mt-3 text-bone-50">{item.name}</p>{item.description?<p className="mt-2 text-sm text-bone-400">{item.description}</p>:null}<p className="mt-4 font-display text-2xl text-bone-50">{formatMznFromCents(item.price)}</p><Botao className="mt-4" type="button" onClick={()=>void buy(item.id)}>{t('phase3.bundles.buy')}</Botao></Ficha>)}</div>{!items.length&&!error?<EstadoVazio title={t('phase3.bundles.emptyTitle')} body={t('phase3.bundles.emptyBody')}/>:null}</PageFrame>;
}

export function CreatorBundlesPage() {
  const { t } = useTranslation();
  const [channels,setChannels]=useState<Channel[]>([]); const [posts,setPosts]=useState<{id:string;caption:string|null}[]>([]); const [bundles,setBundles]=useState<Bundle[]>([]);
  const [channel,setChannel]=useState(''); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [price,setPrice]=useState(''); const [selected,setSelected]=useState<string[]>([]); const [error,setError]=useState<string|null>(null);
  const load=async()=>{if(!supabase)return;try{const [c,p,b]=await Promise.all([phase3Rows<Channel>(supabase,'channels','id,display_name'),phase3Rows<{id:string;caption:string|null}>(supabase,'posts','id,caption'),phase3Rows<Bundle>(supabase,'bundles','id,channel_id,name,description,price,status')]);setChannels(c);setPosts(p);setBundles(b);if(!channel&&c[0])setChannel(c[0].id);}catch(e:unknown){setError(e instanceof Error?e.message:'bundle_error');}};
  useEffect(()=>{void load();},[]);
  const create=async(e:FormEvent)=>{e.preventDefault();try{await phase3Rpc('create_bundle',{_channel:channel,_name:name,_description:description,_price:Math.round(Number(price)*100),_post_ids:selected});setName('');setDescription('');setPrice('');setSelected([]);await load();}catch(e:unknown){setError(e instanceof Error?e.message:'bundle_create_error');}};
  if(!supabase)return <PageFrame eyebrow={t('phase3.bundles.eyebrow')} title={t('phase3.bundles.creatorTitle')} intro={t('phase3.bundles.creatorIntro')}><EstadoVazio title={t('phase3.backend.title')} body={t('phase3.backend.notConfigured')}/></PageFrame>;
  return <PageFrame eyebrow={t('phase3.bundles.eyebrow')} title={t('phase3.bundles.creatorTitle')} intro={t('phase3.bundles.creatorIntro')}><ErrorMessage error={error}/><Ficha><form onSubmit={create} className="space-y-4"><select value={channel} onChange={(e)=>setChannel(e.target.value)} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50">{channels.map((c)=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><input value={name} onChange={(e)=>setName(e.target.value)} required placeholder={t('phase3.bundles.name')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><input value={price} onChange={(e)=>setPrice(e.target.value)} required placeholder={t('phase3.bundles.price')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><textarea value={description} onChange={(e)=>setDescription(e.target.value)} placeholder={t('phase3.bundles.description')} className="min-h-24 w-full rounded-md bg-ink-900 p-3 text-bone-50"/><div className="grid gap-2">{posts.map((post)=><label key={post.id} className="flex items-center gap-3 rounded-md border border-bone-50/8 p-3 text-sm text-bone-300"><input type="checkbox" checked={selected.includes(post.id)} onChange={(e)=>setSelected((cur)=>e.target.checked?[...cur,post.id]:cur.filter((id)=>id!==post.id))}/>{post.caption??post.id}</label>)}</div><Botao type="submit"><Package size={18}/>{t('phase3.bundles.create')}</Botao></form></Ficha><div className="mt-6 grid gap-4">{bundles.map((bundle)=><Ficha key={bundle.id}><p className="text-bone-50">{bundle.name}</p><p className="text-sm text-bone-400">{formatMznFromCents(bundle.price)}</p></Ficha>)}</div></PageFrame>;
}

export function CreatorEngagementPage() {
  const { t } = useTranslation(); const client=supabase;
  const [channels,setChannels]=useState<Channel[]>([]); const [channel,setChannel]=useState(''); const [question,setQuestion]=useState(''); const [options,setOptions]=useState(''); const [giveawayTitle,setGiveawayTitle]=useState(''); const [giveawayEnds,setGiveawayEnds]=useState(''); const [winnerCount,setWinnerCount]=useState('1'); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!client)return;void phase3Rows<Channel>(client,'channels','id,display_name').then((rows)=>{setChannels(rows);if(rows[0])setChannel(rows[0].id);}).catch((e:unknown)=>setError(e instanceof Error?e.message:'load_error'));},[client]);
  const createPoll=async(e:FormEvent)=>{e.preventDefault();try{await phase3Rpc('create_poll',{_channel:channel,_question:question,_closes:null,_options:options.split('\n').map((x)=>x.trim()).filter(Boolean)});setQuestion('');setOptions('');}catch(e:unknown){setError(e instanceof Error?e.message:'poll_error');}};
  const createGiveaway=async(e:FormEvent)=>{e.preventDefault();try{await phase3Rpc('create_giveaway',{_channel:channel,_title:giveawayTitle,_description:null,_starts:new Date().toISOString(),_ends:new Date(giveawayEnds).toISOString(),_winner_count:Number(winnerCount),_requires_subscription:true});setGiveawayTitle('');setGiveawayEnds('');}catch(e:unknown){setError(e instanceof Error?e.message:'giveaway_error');}};
  if(!client)return <PageFrame eyebrow={t('phase3.engagement.eyebrow')} title={t('phase3.engagement.creatorTitle')} intro={t('phase3.engagement.creatorIntro')}><EstadoVazio title={t('phase3.backend.title')} body={t('phase3.backend.notConfigured')}/></PageFrame>;
  return <PageFrame eyebrow={t('phase3.engagement.eyebrow')} title={t('phase3.engagement.creatorTitle')} intro={t('phase3.engagement.creatorIntro')}><ErrorMessage error={error}/><div className="grid gap-4 lg:grid-cols-2"><Ficha><div className="flex items-center gap-3"><Poll size={22}/><h2 className="text-lg text-bone-50">{t('phase3.engagement.pollTitle')}</h2></div><form onSubmit={createPoll} className="mt-5 space-y-4"><select value={channel} onChange={(e)=>setChannel(e.target.value)} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50">{channels.map((c)=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><input value={question} onChange={(e)=>setQuestion(e.target.value)} required placeholder={t('phase3.engagement.question')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><textarea value={options} onChange={(e)=>setOptions(e.target.value)} required placeholder={t('phase3.engagement.optionsHint')} className="min-h-24 w-full rounded-md bg-ink-900 p-3 text-bone-50"/><Botao type="submit">{t('phase3.engagement.createPoll')}</Botao></form></Ficha><Ficha><div className="flex items-center gap-3"><Trophy size={22}/><h2 className="text-lg text-bone-50">{t('phase3.engagement.giveawayTitle')}</h2></div><form onSubmit={createGiveaway} className="mt-5 space-y-4"><input value={giveawayTitle} onChange={(e)=>setGiveawayTitle(e.target.value)} required placeholder={t('phase3.engagement.title')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><input type="datetime-local" value={giveawayEnds} onChange={(e)=>setGiveawayEnds(e.target.value)} required className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><input value={winnerCount} onChange={(e)=>setWinnerCount(e.target.value)} required min="1" max="20" inputMode="numeric" placeholder={t('phase3.engagement.winnerCountLabel')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><Botao type="submit">{t('phase3.engagement.createGiveaway')}</Botao></form></Ficha></div></PageFrame>;
}

export function ClientEngagementPage() {
  const { t }=useTranslation(); const client=supabase;
  const [polls,setPolls]=useState<Poll[]>([]); const [options,setOptions]=useState<PollOption[]>([]); const [giveaways,setGiveaways]=useState<Giveaway[]>([]); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!client)return;void Promise.all([phase3Rows<Poll>(client,'polls','id,channel_id,question,closes_at,status'),phase3Rows<PollOption>(client,'poll_options','id,poll_id,label,sort_order'),phase3Rows<Giveaway>(client,'giveaways','id,channel_id,title,winner_count,starts_at,ends_at,status')]).then(([a,b,c])=>{setPolls(a);setOptions(b);setGiveaways(c);}).catch((e:unknown)=>setError(e instanceof Error?e.message:'engagement_error'));},[client]);
  const vote=async(poll:string,option:string)=>{try{await phase3Rpc('cast_poll_vote',{_poll:poll,_option:option});}catch(e:unknown){setError(e instanceof Error?e.message:'vote_error');}};
  const enter=async(id:string)=>{try{await phase3Rpc('enter_giveaway',{_giveaway:id});}catch(e:unknown){setError(e instanceof Error?e.message:'giveaway_enter_error');}};
  if(!client)return <PageFrame eyebrow={t('phase3.engagement.eyebrow')} title={t('phase3.engagement.clientTitle')} intro={t('phase3.engagement.clientIntro')}><EstadoVazio title={t('phase3.backend.title')} body={t('phase3.backend.notConfigured')}/></PageFrame>;
  return <PageFrame eyebrow={t('phase3.engagement.eyebrow')} title={t('phase3.engagement.clientTitle')} intro={t('phase3.engagement.clientIntro')}><ErrorMessage error={error}/><div className="grid gap-4">{polls.map((poll)=><Ficha key={poll.id}><div className="flex items-center gap-3"><Poll size={22}/><p className="text-bone-50">{poll.question}</p></div><div className="mt-4 grid gap-2">{options.filter((o)=>o.poll_id===poll.id).sort((a,b)=>a.sort_order-b.sort_order).map((option)=><Botao key={option.id} type="button" variant="secondary" onClick={()=>void vote(poll.id,option.id)}>{option.label}</Botao>)}</div></Ficha>)}{giveaways.map((g)=><Ficha key={g.id}><div className="flex items-center gap-3"><Trophy size={22}/><p className="text-bone-50">{g.title}</p></div><p className="mt-2 text-sm text-bone-400">{t('phase3.engagement.winnerCount',{count:g.winner_count})}</p><Botao type="button" className="mt-4" onClick={()=>void enter(g.id)}>{t('phase3.engagement.enter')}</Botao></Ficha>)}</div>{!polls.length&&!giveaways.length&&!error?<EstadoVazio title={t('phase3.engagement.emptyTitle')} body={t('phase3.engagement.emptyBody')}/>:null}</PageFrame>;
}

export function CreatorSchedulePage() {
  const { t }=useTranslation(); const client=supabase;
  const [channels,setChannels]=useState<Channel[]>([]); const [channel,setChannel]=useState(''); const [starts,setStarts]=useState(''); const [ends,setEnds]=useState(''); const [area,setArea]=useState(''); const [slots,setSlots]=useState<Slot[]>([]); const [error,setError]=useState<string|null>(null);
  const load=async()=>{if(!client)return;try{const [c,s]=await Promise.all([phase3Rows<Channel>(client,'channels','id,display_name'),phase3Rows<Slot>(client,'availability_slots','id,channel_id,starts_at,ends_at,area_label')]);setChannels(c);setSlots(s);if(!channel&&c[0])setChannel(c[0].id);}catch(e:unknown){setError(e instanceof Error?e.message:'schedule_error');}};
  useEffect(()=>{void load();},[]);
  const create=async(e:FormEvent)=>{e.preventDefault();if(!client)return;try{const {error:insertError}=await client.from('availability_slots').insert({channel_id:channel,starts_at:new Date(starts).toISOString(),ends_at:new Date(ends).toISOString(),area_label:area.trim()||null});if(insertError)throw insertError;setStarts('');setEnds('');setArea('');await load();}catch(e:unknown){setError(e instanceof Error?e.message:'schedule_create_error');}};
  if(!client)return <PageFrame eyebrow={t('phase3.schedule.eyebrow')} title={t('phase3.schedule.title')} intro={t('phase3.schedule.intro')}><EstadoVazio title={t('phase3.backend.title')} body={t('phase3.backend.notConfigured')}/></PageFrame>;
  return <PageFrame eyebrow={t('phase3.schedule.eyebrow')} title={t('phase3.schedule.title')} intro={t('phase3.schedule.intro')}><ErrorMessage error={error}/><Ficha><form onSubmit={create} className="grid gap-4 md:grid-cols-2"><select value={channel} onChange={(e)=>setChannel(e.target.value)} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50">{channels.map((c)=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><input value={area} onChange={(e)=>setArea(e.target.value)} placeholder={t('phase3.schedule.area')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><input type="datetime-local" value={starts} onChange={(e)=>setStarts(e.target.value)} required className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><input type="datetime-local" value={ends} onChange={(e)=>setEnds(e.target.value)} required className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><div className="md:col-span-2"><Botao type="submit"><CalendarBlank size={18}/>{t('phase3.schedule.create')}</Botao></div></form></Ficha><div className="mt-6 grid gap-3">{slots.map((slot)=><Ficha key={slot.id}><p className="text-bone-50">{new Date(slot.starts_at).toLocaleString()}</p><p className="text-sm text-bone-400">{new Date(slot.ends_at).toLocaleString()}{slot.area_label ? ' • ' + slot.area_label : ''}</p></Ficha>)}</div></PageFrame>;
}

export function ClientRankingsPage() {
  const { t }=useTranslation(); const client=supabase; const [creator,setCreator]=useState<Ranking[]>([]); const [fan,setFan]=useState<Ranking[]>([]); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!client)return;void Promise.all([phase3Rows<Ranking>(client,'creator_rankings_weekly','rank,score,channel_id'),phase3Rows<Ranking>(client,'fan_rankings_weekly','rank,score,user_id')]).then(([a,b])=>{setCreator(a.slice(0,10));setFan(b.slice(0,10));}).catch((e:unknown)=>setError(e instanceof Error?e.message:'ranking_error'));},[client]);
  if(!client)return <PageFrame eyebrow={t('phase3.rankings.eyebrow')} title={t('phase3.rankings.title')} intro={t('phase3.rankings.intro')}><EstadoVazio title={t('phase3.backend.title')} body={t('phase3.backend.notConfigured')}/></PageFrame>;
  return <PageFrame eyebrow={t('phase3.rankings.eyebrow')} title={t('phase3.rankings.title')} intro={t('phase3.rankings.intro')}><ErrorMessage error={error}/><div className="grid gap-4 md:grid-cols-2"><Ficha><h2 className="text-lg text-bone-50">{t('phase3.rankings.creators')}</h2><div className="mt-4 space-y-2">{creator.map((row)=><div key={row.rank} className="flex items-center justify-between rounded-md border border-bone-50/8 p-3"><span className="text-bone-50">#{row.rank}</span><span className="text-sm text-bone-400">{row.score}</span></div>)}</div></Ficha><Ficha><h2 className="text-lg text-bone-50">{t('phase3.rankings.fans')}</h2><div className="mt-4 space-y-2">{fan.map((row)=><div key={row.rank} className="flex items-center justify-between rounded-md border border-bone-50/8 p-3"><span className="text-bone-50">#{row.rank}</span><span className="text-sm text-bone-400">{row.score}</span></div>)}</div></Ficha></div></PageFrame>;
}