import { useEffect, useState, type FormEvent } from 'react';
import { CalendarBlank, Gift, Heart, Package, ChartBar, Trophy, UsersThree } from '@phosphor-icons/react';
import { useTranslation } from 'react-i18next';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { Botao } from '@/design/Botao';
import { Ficha } from '@/design/Ficha';
import { EstadoVazio } from '@/design/EstadoVazio';
import { PageFrame } from '@/pages/PageFrame';
import { formatMznFromCents } from '@/lib/money';
import { supabase } from '@/lib/supabase';
import { phase3Rows, phase3Rpc } from '@/lib/phase3Api';

type Channel = { id: string; display_name: string };
type Tier = { id: string; channel_id: string; name: string; rank: number; price_month: number };
type GiftRow = { id: string; name: string; price: number; active: boolean };
type Bundle = { id: string; channel_id: string; name: string; description: string | null; price: number; status: string };
type Slot = { id: string; channel_id: string; starts_at: string; ends_at: string; area_label: string | null };
type Poll = { id: string; channel_id: string; question: string; closes_at: string | null; status: string };
type PollOption = { id: string; poll_id: string; label: string; sort_order: number };
type Giveaway = { id: string; channel_id: string; title: string; winner_count: number; starts_at: string; ends_at: string; status: string };
type Ranking = { rank: number; score: number; channel_id?: string; user_id?: string };

function ErrorMessage({ error }: { error: string | null }) {
  const { t } = useTranslation();
  return error ? <p role="alert" className="mt-4 text-sm text-danger">{t('phase3.errors.generic')}</p> : null;
}

export function ClientSupportCreatorPage() {
  const { t } = useTranslation();
  const [params] = useSearchParams();
  const channelId = params.get('channel') ?? '';
  const [tiers, setTiers] = useState<Tier[]>([]);
  const [gifts, setGifts] = useState<GiftRow[]>([]);
  const [tip, setTip] = useState('');
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => {
    if (!supabase || !channelId) return;
    void Promise.all([
      phase3Rows<Tier>(supabase, 'subscription_tiers', 'id,channel_id,name,rank,price_month'),
      phase3Rows<GiftRow>(supabase, 'gifts_catalog', 'id,name,price,active')
    ]).then(([a, b]) => { setTiers(a.filter((x) => x.channel_id === channelId)); setGifts(b.filter((x) => x.active)); })
      .catch((e: unknown) => setError(e instanceof Error ? e.message : 'load_error'));
  }, [channelId]);
  const subscribe = async (tier: Tier, period: number) => { setBusy(true); setError(null); try { await phase3Rpc('subscribe', { _tier: tier.id, _period: period, _idem: crypto.randomUUID() }); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'subscribe_error'); } finally { setBusy(false); } };
  const sendTip = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(null); try { await phase3Rpc('send_tip', { _channel: channelId, _amount: Math.round(Number(tip) * 100), _message: message, _idem: crypto.randomUUID() }); setTip(''); setMessage(''); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'tip_error'); } finally { setBusy(false); } };
  const sendGift = async (gift: GiftRow) => { setBusy(true); setError(null); try { await phase3Rpc('send_gift', { _channel: channelId, _gift: gift.id, _quantity: 1, _message: message, _idem: crypto.randomUUID() }); setMessage(''); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'gift_error'); } finally { setBusy(false); } };
  if (!supabase) return <PageFrame eyebrow={t('phase3Advanced.support.eyebrow')} title={t('phase3Advanced.support.title')} intro={t('phase3Advanced.support.intro')}><EstadoVazio title={t('phase3.backend.title')} body={t('phase3.backend.notConfigured')} /></PageFrame>;
  if (!channelId) return <PageFrame eyebrow={t('phase3Advanced.support.eyebrow')} title={t('phase3Advanced.support.title')} intro={t('phase3Advanced.support.intro')}><EstadoVazio title={t('phase3Advanced.support.missingChannel')} body={t('phase3Advanced.support.missingChannelBody')} /></PageFrame>;
  return <PageFrame eyebrow={t('phase3Advanced.support.eyebrow')} title={t('phase3Advanced.support.title')} intro={t('phase3Advanced.support.intro')}><ErrorMessage error={error}/><div className="grid gap-4 lg:grid-cols-2"><Ficha><div className="flex items-center gap-3"><Heart size={22}/><h2 className="text-lg text-bone-50">{t('phase3Advanced.support.tipTitle')}</h2></div><form onSubmit={sendTip} className="mt-5 space-y-4"><input value={tip} onChange={(e)=>setTip(e.target.value)} required min="1" inputMode="decimal" placeholder={t('phase3Advanced.support.amount')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><input value={message} onChange={(e)=>setMessage(e.target.value)} maxLength={500} placeholder={t('phase3Advanced.support.message')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><Botao type="submit" loading={busy}>{t('phase3Advanced.support.sendTip')}</Botao></form></Ficha><Ficha><div className="flex items-center gap-3"><Gift size={22}/><h2 className="text-lg text-bone-50">{t('phase3Advanced.support.giftsTitle')}</h2></div><div className="mt-5 grid gap-3">{gifts.map((gift)=><div key={gift.id} className="flex items-center justify-between gap-4 rounded-md border border-bone-50/8 p-3"><div><p className="text-bone-50">{gift.name}</p><p className="text-sm text-bone-400">{formatMznFromCents(gift.price)}</p></div><Botao type="button" disabled={busy} onClick={()=>void sendGift(gift)}>{t('phase3Advanced.support.sendGift')}</Botao></div>)}{!gifts.length?<EstadoVazio title={t('phase3Advanced.support.noGifts')} body={t('phase3Advanced.support.noGiftsBody')}/>:null}</div></Ficha></div><Ficha className="mt-6"><div className="flex items-center gap-3"><UsersThree size={22}/><h2 className="text-lg text-bone-50">{t('phase3Advanced.support.subscriptionsTitle')}</h2></div><div className="mt-5 grid gap-4 md:grid-cols-2">{tiers.map((tier)=><div key={tier.id} className="rounded-md border border-bone-50/8 p-4"><p className="text-bone-50">{tier.name}</p><p className="mt-2 font-display text-2xl text-bone-50">{formatMznFromCents(tier.price_month)}</p><div className="mt-4 flex flex-wrap gap-2">{[1,3,6,12].map((period)=><Botao key={period} type="button" disabled={busy} onClick={()=>void subscribe(tier,period)}>{t('phase3Advanced.support.months',{count:period})}</Botao>)}</div></div>)}{!tiers.length?<EstadoVazio title={t('phase3Advanced.support.noTiers')} body={t('phase3Advanced.support.noTiersBody')}/>:null}</div></Ficha></PageFrame>;
}

export function ClientBundlesPage() {
  const { t } = useTranslation();
  const [items, setItems] = useState<Bundle[]>([]); const [error, setError] = useState<string | null>(null);
  const load = async () => { if (!supabase) return; try { setItems(await phase3Rows<Bundle>(supabase, 'bundles', 'id,channel_id,name,description,price,status')); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'bundle_error'); } };
  useEffect(() => { void load(); }, []);
  const buy = async (id: string) => { try { await phase3Rpc('buy_bundle', { _bundle: id, _idem: crypto.randomUUID() }); await load(); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'bundle_buy_error'); } };
  return <PageFrame eyebrow={t('phase3Advanced.bundles.eyebrow')} title={t('phase3Advanced.bundles.clientTitle')} intro={t('phase3Advanced.bundles.clientIntro')}><ErrorMessage error={error}/><div className="grid gap-4 md:grid-cols-2">{items.filter((x)=>x.status==='active').map((item)=><Ficha key={item.id}><Package size={22}/><p className="mt-3 text-bone-50">{item.name}</p>{item.description?<p className="mt-2 text-sm text-bone-400">{item.description}</p>:null}<p className="mt-4 font-display text-2xl text-bone-50">{formatMznFromCents(item.price)}</p><Botao className="mt-4" type="button" onClick={()=>void buy(item.id)}>{t('phase3Advanced.bundles.buy')}</Botao></Ficha>)}</div>{!items.length&&!error?<EstadoVazio title={t('phase3Advanced.bundles.emptyTitle')} body={t('phase3Advanced.bundles.emptyBody')}/>:null}</PageFrame>;
}

export function CreatorBundlesPage() {
  const { t } = useTranslation();
  const [channels,setChannels]=useState<Channel[]>([]); const [posts,setPosts]=useState<{id:string;caption:string|null}[]>([]); const [bundles,setBundles]=useState<Bundle[]>([]);
  const [channel,setChannel]=useState(''); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [price,setPrice]=useState(''); const [selected,setSelected]=useState<string[]>([]); const [error,setError]=useState<string|null>(null);
  const load=async()=>{if(!supabase)return;try{const [c,p,b]=await Promise.all([phase3Rows<Channel>(supabase,'channels','id,display_name'),phase3Rows<{id:string;caption:string|null}>(supabase,'posts','id,caption'),phase3Rows<Bundle>(supabase,'bundles','id,channel_id,name,description,price,status')]);setChannels(c);setPosts(p);setBundles(b);if(!channel&&c[0])setChannel(c[0].id);}catch(e:unknown){setError(e instanceof Error?e.message:'bundle_error');}};
  useEffect(()=>{void load();},[]);
  const create=async(e:FormEvent)=>{e.preventDefault();try{await phase3Rpc('create_bundle',{_channel:channel,_name:name,_description:description,_price:Math.round(Number(price)*100),_post_ids:selected});setName('');setDescription('');setPrice('');setSelected([]);await load();}catch(e:unknown){setError(e instanceof Error?e.message:'bundle_create_error');}};
  if(!supabase)return <PageFrame eyebrow={t('phase3Advanced.bundles.eyebrow')} title={t('phase3Advanced.bundles.creatorTitle')} intro={t('phase3Advanced.bundles.creatorIntro')}><EstadoVazio title={t('phase3.backend.title')} body={t('phase3.backend.notConfigured')}/></PageFrame>;
  return <PageFrame eyebrow={t('phase3Advanced.bundles.eyebrow')} title={t('phase3Advanced.bundles.creatorTitle')} intro={t('phase3Advanced.bundles.creatorIntro')}><ErrorMessage error={error}/><Ficha><form onSubmit={create} className="space-y-4"><select value={channel} onChange={(e)=>setChannel(e.target.value)} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50">{channels.map((c)=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><input value={name} onChange={(e)=>setName(e.target.value)} required placeholder={t('phase3Advanced.bundles.name')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><input value={price} onChange={(e)=>setPrice(e.target.value)} required placeholder={t('phase3Advanced.bundles.price')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><textarea value={description} onChange={(e)=>setDescription(e.target.value)} placeholder={t('phase3Advanced.bundles.description')} className="min-h-24 w-full rounded-md bg-ink-900 p-3 text-bone-50"/><div className="grid gap-2">{posts.map((post)=><label key={post.id} className="flex items-center gap-3 rounded-md border border-bone-50/8 p-3 text-sm text-bone-300"><input type="checkbox" checked={selected.includes(post.id)} onChange={(e)=>setSelected((cur)=>e.target.checked?[...cur,post.id]:cur.filter((id)=>id!==post.id))}/>{post.caption??post.id}</label>)}</div><Botao type="submit"><Package size={18}/>{t('phase3Advanced.bundles.create')}</Botao></form></Ficha><div className="mt-6 grid gap-4">{bundles.map((bundle)=><Ficha key={bundle.id}><p className="text-bone-50">{bundle.name}</p><p className="text-sm text-bone-400">{formatMznFromCents(bundle.price)}</p></Ficha>)}</div></PageFrame>;
}

export function CreatorEngagementPage() {
  const { t } = useTranslation(); const client=supabase;
  const [channels,setChannels]=useState<Channel[]>([]); const [channel,setChannel]=useState(''); const [question,setQuestion]=useState(''); const [options,setOptions]=useState(''); const [giveawayTitle,setGiveawayTitle]=useState(''); const [giveawayEnds,setGiveawayEnds]=useState(''); const [winnerCount,setWinnerCount]=useState('1'); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!client)return;void phase3Rows<Channel>(client,'channels','id,display_name').then((rows)=>{setChannels(rows);if(rows[0])setChannel(rows[0].id);}).catch((e:unknown)=>setError(e instanceof Error?e.message:'load_error'));},[client]);
  const createPoll=async(e:FormEvent)=>{e.preventDefault();try{await phase3Rpc('create_poll',{_channel:channel,_question:question,_closes:null,_options:options.split('\n').map((x)=>x.trim()).filter(Boolean)});setQuestion('');setOptions('');}catch(e:unknown){setError(e instanceof Error?e.message:'poll_error');}};
  const createGiveaway=async(e:FormEvent)=>{e.preventDefault();try{await phase3Rpc('create_giveaway',{_channel:channel,_title:giveawayTitle,_description:null,_starts:new Date().toISOString(),_ends:new Date(giveawayEnds).toISOString(),_winner_count:Number(winnerCount),_requires_subscription:true});setGiveawayTitle('');setGiveawayEnds('');}catch(e:unknown){setError(e instanceof Error?e.message:'giveaway_error');}};
  if(!client)return <PageFrame eyebrow={t('phase3Advanced.engagement.eyebrow')} title={t('phase3Advanced.engagement.creatorTitle')} intro={t('phase3Advanced.engagement.creatorIntro')}><EstadoVazio title={t('phase3.backend.title')} body={t('phase3.backend.notConfigured')}/></PageFrame>;
  return <PageFrame eyebrow={t('phase3Advanced.engagement.eyebrow')} title={t('phase3Advanced.engagement.creatorTitle')} intro={t('phase3Advanced.engagement.creatorIntro')}><ErrorMessage error={error}/><div className="grid gap-4 lg:grid-cols-2"><Ficha><div className="flex items-center gap-3"><ChartBar size={22}/><h2 className="text-lg text-bone-50">{t('phase3Advanced.engagement.pollTitle')}</h2></div><form onSubmit={createPoll} className="mt-5 space-y-4"><select value={channel} onChange={(e)=>setChannel(e.target.value)} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50">{channels.map((c)=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><input value={question} onChange={(e)=>setQuestion(e.target.value)} required placeholder={t('phase3Advanced.engagement.question')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><textarea value={options} onChange={(e)=>setOptions(e.target.value)} required placeholder={t('phase3Advanced.engagement.optionsHint')} className="min-h-24 w-full rounded-md bg-ink-900 p-3 text-bone-50"/><Botao type="submit">{t('phase3Advanced.engagement.createPoll')}</Botao></form></Ficha><Ficha><div className="flex items-center gap-3"><Trophy size={22}/><h2 className="text-lg text-bone-50">{t('phase3Advanced.engagement.giveawayTitle')}</h2></div><form onSubmit={createGiveaway} className="mt-5 space-y-4"><input value={giveawayTitle} onChange={(e)=>setGiveawayTitle(e.target.value)} required placeholder={t('phase3Advanced.engagement.title')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><input type="datetime-local" value={giveawayEnds} onChange={(e)=>setGiveawayEnds(e.target.value)} required className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><input value={winnerCount} onChange={(e)=>setWinnerCount(e.target.value)} required min="1" max="20" inputMode="numeric" placeholder={t('phase3Advanced.engagement.winnerCountLabel')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><Botao type="submit">{t('phase3Advanced.engagement.createGiveaway')}</Botao></form></Ficha></div></PageFrame>;
}

export function ClientEngagementPage() {
  const { t }=useTranslation(); const client=supabase;
  const [polls,setPolls]=useState<Poll[]>([]); const [options,setOptions]=useState<PollOption[]>([]); const [giveaways,setGiveaways]=useState<Giveaway[]>([]); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!client)return;void Promise.all([phase3Rows<Poll>(client,'polls','id,channel_id,question,closes_at,status'),phase3Rows<PollOption>(client,'poll_options','id,poll_id,label,sort_order'),phase3Rows<Giveaway>(client,'giveaways','id,channel_id,title,winner_count,starts_at,ends_at,status')]).then(([a,b,c])=>{setPolls(a);setOptions(b);setGiveaways(c);}).catch((e:unknown)=>setError(e instanceof Error?e.message:'engagement_error'));},[client]);
  const vote=async(poll:string,option:string)=>{try{await phase3Rpc('cast_poll_vote',{_poll:poll,_option:option});}catch(e:unknown){setError(e instanceof Error?e.message:'vote_error');}};
  const enter=async(id:string)=>{try{await phase3Rpc('enter_giveaway',{_giveaway:id});}catch(e:unknown){setError(e instanceof Error?e.message:'giveaway_enter_error');}};
  if(!client)return <PageFrame eyebrow={t('phase3Advanced.engagement.eyebrow')} title={t('phase3Advanced.engagement.clientTitle')} intro={t('phase3Advanced.engagement.clientIntro')}><EstadoVazio title={t('phase3.backend.title')} body={t('phase3.backend.notConfigured')}/></PageFrame>;
  return <PageFrame eyebrow={t('phase3Advanced.engagement.eyebrow')} title={t('phase3Advanced.engagement.clientTitle')} intro={t('phase3Advanced.engagement.clientIntro')}><ErrorMessage error={error}/><div className="grid gap-4">{polls.map((poll)=><Ficha key={poll.id}><div className="flex items-center gap-3"><ChartBar size={22}/><p className="text-bone-50">{poll.question}</p></div><div className="mt-4 grid gap-2">{options.filter((o)=>o.poll_id===poll.id).sort((a,b)=>a.sort_order-b.sort_order).map((option)=><Botao key={option.id} type="button" variant="outline" onClick={()=>void vote(poll.id,option.id)}>{option.label}</Botao>)}</div></Ficha>)}{giveaways.map((g)=><Ficha key={g.id}><div className="flex items-center gap-3"><Trophy size={22}/><p className="text-bone-50">{g.title}</p></div><p className="mt-2 text-sm text-bone-400">{t('phase3Advanced.engagement.winnerCount',{count:g.winner_count})}</p><Botao type="button" className="mt-4" onClick={()=>void enter(g.id)}>{t('phase3Advanced.engagement.enter')}</Botao></Ficha>)}</div>{!polls.length&&!giveaways.length&&!error?<EstadoVazio title={t('phase3Advanced.engagement.emptyTitle')} body={t('phase3Advanced.engagement.emptyBody')}/>:null}</PageFrame>;
}

export function CreatorSchedulePage() {
  const { t }=useTranslation(); const client=supabase;
  const [channels,setChannels]=useState<Channel[]>([]); const [channel,setChannel]=useState(''); const [starts,setStarts]=useState(''); const [ends,setEnds]=useState(''); const [area,setArea]=useState(''); const [slots,setSlots]=useState<Slot[]>([]); const [error,setError]=useState<string|null>(null);
  const load=async()=>{if(!client)return;try{const [c,s]=await Promise.all([phase3Rows<Channel>(client,'channels','id,display_name'),phase3Rows<Slot>(client,'availability_slots','id,channel_id,starts_at,ends_at,area_label')]);setChannels(c);setSlots(s);if(!channel&&c[0])setChannel(c[0].id);}catch(e:unknown){setError(e instanceof Error?e.message:'schedule_error');}};
  useEffect(()=>{void load();},[]);
  const create=async(e:FormEvent)=>{e.preventDefault();if(!client)return;try{const {error:insertError}=await client.from('availability_slots').insert({channel_id:channel,starts_at:new Date(starts).toISOString(),ends_at:new Date(ends).toISOString(),area_label:area.trim()||null});if(insertError)throw insertError;setStarts('');setEnds('');setArea('');await load();}catch(e:unknown){setError(e instanceof Error?e.message:'schedule_create_error');}};
  if(!client)return <PageFrame eyebrow={t('phase3Advanced.schedule.eyebrow')} title={t('phase3Advanced.schedule.title')} intro={t('phase3Advanced.schedule.intro')}><EstadoVazio title={t('phase3.backend.title')} body={t('phase3.backend.notConfigured')}/></PageFrame>;
  return <PageFrame eyebrow={t('phase3Advanced.schedule.eyebrow')} title={t('phase3Advanced.schedule.title')} intro={t('phase3Advanced.schedule.intro')}><ErrorMessage error={error}/><Ficha><form onSubmit={create} className="grid gap-4 md:grid-cols-2"><select value={channel} onChange={(e)=>setChannel(e.target.value)} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50">{channels.map((c)=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><input value={area} onChange={(e)=>setArea(e.target.value)} placeholder={t('phase3Advanced.schedule.area')} className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><input type="datetime-local" value={starts} onChange={(e)=>setStarts(e.target.value)} required className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><input type="datetime-local" value={ends} onChange={(e)=>setEnds(e.target.value)} required className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><div className="md:col-span-2"><Botao type="submit"><CalendarBlank size={18}/>{t('phase3Advanced.schedule.create')}</Botao></div></form></Ficha><div className="mt-6 grid gap-3">{slots.map((slot)=><Ficha key={slot.id}><p className="text-bone-50">{new Date(slot.starts_at).toLocaleString()}</p><p className="text-sm text-bone-400">{new Date(slot.ends_at).toLocaleString()}{slot.area_label ? ' • ' + slot.area_label : ''}</p></Ficha>)}</div></PageFrame>;
}

export function ClientRankingsPage() {
  const { t }=useTranslation(); const client=supabase; const [creator,setCreator]=useState<Ranking[]>([]); const [fan,setFan]=useState<Ranking[]>([]); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!client)return;void Promise.all([phase3Rows<Ranking>(client,'creator_rankings_weekly','rank,score,channel_id'),phase3Rows<Ranking>(client,'fan_rankings_weekly','rank,score,user_id')]).then(([a,b])=>{setCreator(a.slice(0,10));setFan(b.slice(0,10));}).catch((e:unknown)=>setError(e instanceof Error?e.message:'ranking_error'));},[client]);
  if(!client)return <PageFrame eyebrow={t('phase3Advanced.rankings.eyebrow')} title={t('phase3Advanced.rankings.title')} intro={t('phase3Advanced.rankings.intro')}><EstadoVazio title={t('phase3.backend.title')} body={t('phase3.backend.notConfigured')}/></PageFrame>;
  return <PageFrame eyebrow={t('phase3Advanced.rankings.eyebrow')} title={t('phase3Advanced.rankings.title')} intro={t('phase3Advanced.rankings.intro')}><ErrorMessage error={error}/><div className="grid gap-4 md:grid-cols-2"><Ficha><h2 className="text-lg text-bone-50">{t('phase3Advanced.rankings.creators')}</h2><div className="mt-4 space-y-2">{creator.map((row)=><div key={row.rank} className="flex items-center justify-between rounded-md border border-bone-50/8 p-3"><span className="text-bone-50">#{row.rank}</span><span className="text-sm text-bone-400">{row.score}</span></div>)}</div></Ficha><Ficha><h2 className="text-lg text-bone-50">{t('phase3Advanced.rankings.fans')}</h2><div className="mt-4 space-y-2">{fan.map((row)=><div key={row.rank} className="flex items-center justify-between rounded-md border border-bone-50/8 p-3"><span className="text-bone-50">#{row.rank}</span><span className="text-sm text-bone-400">{row.score}</span></div>)}</div></Ficha></div></PageFrame>;
}

type WalletSummary = { wallet: number; pending: number; available: number };
type LiveSession = { id: string; channel_id: string; title: string; mode: 'free' | 'paid'; price: number | null; status: string };
type Auction = { id: string; channel_id: string; title: string; minimum_bid: number; ends_at: string; status: string };
type Product = { id: string; channel_id: string; name: string; description: string | null; price: number; stock: number; active: boolean };
type RequestRow = { id: string; channel_id: string; brief: string; budget: number; status: string };
type DailyAnalytics = { day: string; views: number; unique_viewers: number; messages: number; sales: number; gross_amount: number; tips: number; live_minutes: number };
type Dashboard = { pending: number; available: number; followers: number; live: number; goals: number };
type Loyalty = { points: number; lifetime_points: number; level: string | null; current_streak: number };

function Phase3Error({ error }: { error: string | null }) {
  const { t } = useTranslation();
  return error ? <p role="alert" className="mt-4 text-sm text-danger">{t('phase3.errors.generic')}</p> : null;
}

export function ClientWalletRealPage() {
  const { t } = useTranslation();
  const [data, setData] = useState<WalletSummary | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { void phase3Rpc<WalletSummary>('get_wallet_summary').then(setData).catch(() => setError(t('phase3.errors.generic'))); }, [t]);
  return <PageFrame eyebrow={t('phase3.wallet.eyebrow')} title={t('experience.pages.wallet.title')} intro={t('phase3.wallet.intro')}><Phase3Error error={error}/>{data ? <div className="grid gap-4 md:grid-cols-3"><Ficha><p className="text-xs uppercase text-bone-500">{t('phase3.wallet.wallet')}</p><p className="mt-3 font-display text-4xl text-bone-50">{formatMznFromCents(data.wallet)}</p></Ficha><Ficha><p className="text-xs uppercase text-bone-500">{t('phase3.wallet.pending')}</p><p className="mt-3 font-display text-4xl text-bone-50">{formatMznFromCents(data.pending)}</p></Ficha><Ficha><p className="text-xs uppercase text-bone-500">{t('phase3.wallet.available')}</p><p className="mt-3 font-display text-4xl text-bone-50">{formatMznFromCents(data.available)}</p></Ficha></div> : !error ? <EstadoVazio title={t('phase3.backend.title')} body={t('common.loading')} /> : null}</PageFrame>;
}

export function ClientLiveListPage() {
  const { t } = useTranslation();
  const [items,setItems]=useState<LiveSession[]>([]); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!supabase)return;void phase3Rows<LiveSession>(supabase,'live_sessions','id,channel_id,title,mode,price,status').then(setItems).catch(()=>setError(t('phase3.errors.generic')));},[t]);
  const buy=async(id:string)=>{try{await phase3Rpc('buy_live_ticket',{_session:id,_idem:crypto.randomUUID()});window.location.assign('/live/'+id);}catch{setError(t('phase3.errors.generic'));}};
  return <PageFrame eyebrow={t('phase3.live.eyebrow')} title={t('phase3.live.listTitle')} intro={t('phase3.live.intro')}><Phase3Error error={error}/><div className="grid gap-4 md:grid-cols-2">{items.map(item=><Ficha key={item.id}><p className="text-bone-50">{item.title}</p><p className="mt-2 text-sm text-bone-400">{item.mode==='paid'&&item.price?formatMznFromCents(item.price):t('phase3.live.mode.free')}</p>{item.mode==='paid'?<Botao className="mt-4" type="button" onClick={()=>void buy(item.id)}>{t('phase3.live.buyTicket')}</Botao>:<Link className="mt-4 inline-flex min-h-11 items-center rounded-md border border-bone-50/10 px-4 text-sm text-bone-50" to={'/live/'+item.id}>{t('phase3.live.join')}</Link>}</Ficha>)}</div>{!items.length&&!error?<EstadoVazio title={t('phase3.live.emptyTitle')} body={t('phase3.live.emptyBody')}/>:null}</PageFrame>;
}

export function ClientLiveRoomPage() {
  const { t }=useTranslation(); const { sessionId='' }=useParams(); const [error,setError]=useState<string|null>(null); const [connected,setConnected]=useState(false);
  const connect=async()=>{try{const data=await phase3Edge<{token:string;url:string}>('livekit-token',{sessionId});const {Room}=await import('livekit-client');const room=new Room();await room.connect(data.url,data.token);setConnected(true);return()=>void room.disconnect();}catch{setError(t('phase3.errors.generic'));}};
  return <PageFrame eyebrow={t('phase3.live.eyebrow')} title={t('phase3.live.title')} intro={t('phase3.live.intro')}><Phase3Error error={error}/>{sessionId?<Ficha><p className="text-sm text-bone-300">{t('phase3.live.connection')}</p><Botao className="mt-4" type="button" onClick={()=>void connect()}>{connected?t('phase3.live.leave'):t('phase3.live.join')}</Botao></Ficha>:<EstadoVazio title={t('phase3.backend.errorTitle')} body={t('phase3.live.missingSession')}/>}</PageFrame>;
}

export function ClientCustomRequestPage() {
  const { t }=useTranslation(); const [params]=useSearchParams(); const channel=params.get('channel')??''; const [brief,setBrief]=useState(''); const [budget,setBudget]=useState(''); const [error,setError]=useState<string|null>(null);
  const submit=async(e:FormEvent)=>{e.preventDefault();try{if(!channel)throw new Error();await phase3Rpc('create_custom_request',{_channel:channel,_brief:brief,_budget:Math.round(Number(budget)*100),_idem:crypto.randomUUID()});setBrief('');setBudget('');}catch{setError(t('phase3.errors.generic'));}};
  return <PageFrame eyebrow={t('phase3.requests.eyebrow')} title={t('phase3.requests.clientTitle')} intro={t('phase3.requests.clientIntro')}><Phase3Error error={error}/><Ficha><form onSubmit={submit} className="space-y-4"><textarea value={brief} onChange={e=>setBrief(e.target.value)} required minLength={10} maxLength={5000} className="min-h-32 w-full rounded-md bg-ink-900 p-3 text-bone-50"/><input value={budget} onChange={e=>setBudget(e.target.value)} required inputMode="decimal" className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><Botao type="submit">{t('phase3.requests.submit')}</Botao></form></Ficha></PageFrame>;
}

export function ClientAuctionPage() {
  const { t }=useTranslation(); const { auctionId='' }=useParams(); const [auction,setAuction]=useState<Auction|null>(null); const [bid,setBid]=useState(''); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!supabase||!auctionId)return;void phase3Rows<Auction>(supabase,'auctions','id,channel_id,title,minimum_bid,ends_at,status').then(rows=>setAuction(rows.find(x=>x.id===auctionId)??null)).catch(()=>setError(t('phase3.errors.generic')));},[auctionId,t]);
  const place=async(e:FormEvent)=>{e.preventDefault();try{await phase3Rpc('place_bid',{_auction:auctionId,_amount:Math.round(Number(bid)*100),_idem:crypto.randomUUID()});setBid('');}catch{setError(t('phase3.errors.generic'));}};
  return <PageFrame eyebrow={t('phase3.auction.eyebrow')} title={auction?.title??t('phase3.auction.title')} intro={t('phase3.auction.intro')}><Phase3Error error={error}/>{auction?<Ficha><p className="text-sm text-bone-400">{t('phase3.auction.minimum')}</p><p className="mt-2 font-display text-3xl text-bone-50">{formatMznFromCents(auction.minimum_bid)}</p><form onSubmit={place} className="mt-4 flex gap-3"><input value={bid} onChange={e=>setBid(e.target.value)} required inputMode="decimal" className="min-h-11 flex-1 rounded-md bg-ink-900 px-3 text-bone-50"/><Botao type="submit">{t('phase3.auction.bid')}</Botao></form></Ficha>:!error?<EstadoVazio title={t('phase3.backend.title')} body={t('common.loading')}/>:null}</PageFrame>;
}

export function ClientStorePage() {
  const { t }=useTranslation(); const [items,setItems]=useState<Product[]>([]); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!supabase)return;void phase3Rows<Product>(supabase,'products','id,channel_id,name,description,price,stock,active').then(setItems).catch(()=>setError(t('phase3.errors.generic')));},[t]);
  const buy=async(id:string)=>{try{await phase3Rpc('create_order',{_items:[{product_id:id,quantity:1}],_shipping:{},_idem:crypto.randomUUID()});}catch{setError(t('phase3.errors.generic'));}};
  return <PageFrame eyebrow={t('phase3.store.eyebrow')} title={t('phase3.store.clientTitle')} intro={t('phase3.store.clientIntro')}><Phase3Error error={error}/><div className="grid gap-4 md:grid-cols-3">{items.filter(x=>x.active&&x.stock>0).map(item=><Ficha key={item.id}><p className="text-bone-50">{item.name}</p><p className="mt-3 font-display text-2xl text-bone-50">{formatMznFromCents(item.price)}</p><Botao className="mt-4" type="button" onClick={()=>void buy(item.id)}>{t('phase3.store.buy')}</Botao></Ficha>)}</div>{!items.length&&!error?<EstadoVazio title={t('phase3.store.emptyTitle')} body={t('phase3.store.emptyBody')}/>:null}</PageFrame>;
}

export function CreatorRequestsAdvancedPage() {
  const { t }=useTranslation(); const [items,setItems]=useState<RequestRow[]>([]); const [error,setError]=useState<string|null>(null);
  const load=async()=>{if(!supabase)return;try{setItems(await phase3Rows<RequestRow>(supabase,'custom_requests','id,channel_id,brief,budget,status'));}catch{setError(t('phase3.errors.generic'));}};
  useEffect(()=>{void load();},[]);
  const act=async(id:string,status:string)=>{try{await phase3Rpc('update_custom_request',{_request:id,_status:status});await load();}catch{setError(t('phase3.errors.generic'));}};
  return <PageFrame eyebrow={t('phase3.requests.eyebrow')} title={t('phase3.requests.creatorTitle')} intro={t('phase3.requests.creatorIntro')}><Phase3Error error={error}/><div className="grid gap-4">{items.map(item=><Ficha key={item.id}><p className="text-bone-50">{item.brief}</p><p className="mt-2 font-display text-2xl text-bone-50">{formatMznFromCents(item.budget)}</p><p className="mt-1 text-xs text-bone-500">{item.status}</p>{item.status==='pending'?<div className="mt-4 flex gap-2"><Botao type="button" onClick={()=>void act(item.id,'accepted')}>{t('phase3.requests.accept')}</Botao><Botao type="button" variant="outline" onClick={()=>void act(item.id,'declined')}>{t('phase3.requests.decline')}</Botao></div>:item.status==='accepted'?<Botao className="mt-4" type="button" onClick={()=>void act(item.id,'in_progress')}>{t('phase3.requests.start')}</Botao>:item.status==='in_progress'?<Botao className="mt-4" type="button" onClick={()=>void act(item.id,'delivered')}>{t('phase3.requests.deliver')}</Botao>:null}</Ficha>)}</div>{!items.length&&!error?<EstadoVazio title={t('phase3.requests.emptyTitle')} body={t('phase3.requests.emptyBody')}/>:null}</PageFrame>;
}

export function CreatorAuctionsAdvancedPage() {
  const { t }=useTranslation(); const [channels,setChannels]=useState<Channel[]>([]); const [items,setItems]=useState<Auction[]>([]); const [channel,setChannel]=useState(''); const [title,setTitle]=useState(''); const [minimum,setMinimum]=useState(''); const [ends,setEnds]=useState(''); const [error,setError]=useState<string|null>(null);
  const load=async()=>{if(!supabase)return;try{setItems(await phase3Rows<Auction>(supabase,'auctions','id,channel_id,title,minimum_bid,ends_at,status'));}catch{setError(t('phase3.errors.generic'));}};
  useEffect(()=>{if(!supabase)return;void Promise.all([phase3Rows<Channel>(supabase,'channels','id,display_name'),load()]).then(([c])=>{setChannels(c);if(c[0])setChannel(c[0].id);});},[]);
  const create=async(e:FormEvent)=>{e.preventDefault();try{await phase3Rpc('create_auction',{_channel:channel,_title:title,_description:null,_minimum:Math.round(Number(minimum)*100),_starts:new Date().toISOString(),_ends:new Date(ends).toISOString(),_post:null});setTitle('');setMinimum('');setEnds('');await load();}catch{setError(t('phase3.errors.generic'));}};
  return <PageFrame eyebrow={t('phase3.auction.eyebrow')} title={t('phase3.auction.creatorTitle')} intro={t('phase3.auction.creatorIntro')}><Phase3Error error={error}/><Ficha><form onSubmit={create} className="grid gap-4 md:grid-cols-2"><select value={channel} onChange={e=>setChannel(e.target.value)} className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50">{channels.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><input value={title} onChange={e=>setTitle(e.target.value)} required className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><input value={minimum} onChange={e=>setMinimum(e.target.value)} required inputMode="decimal" className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><input type="datetime-local" value={ends} onChange={e=>setEnds(e.target.value)} required className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><Botao type="submit">{t('phase3.auction.create')}</Botao></form></Ficha></PageFrame>;
}

export function CreatorStoreAdvancedPage() {
  const { t }=useTranslation(); const [items,setItems]=useState<Product[]>([]); const [channel,setChannel]=useState(''); const [channels,setChannels]=useState<Channel[]>([]); const [name,setName]=useState(''); const [price,setPrice]=useState(''); const [stock,setStock]=useState(''); const [error,setError]=useState<string|null>(null);
  const load=async()=>{if(!supabase)return;try{setItems(await phase3Rows<Product>(supabase,'products','id,channel_id,name,description,price,stock,active'));}catch{setError(t('phase3.errors.generic'));}};
  useEffect(()=>{if(!supabase)return;void Promise.all([phase3Rows<Channel>(supabase,'channels','id,display_name'),load()]).then(([c])=>{setChannels(c);if(c[0])setChannel(c[0].id);});},[]);
  const create=async(e:FormEvent)=>{e.preventDefault();try{if(!supabase)throw new Error();const {error:insertError}=await supabase.from('products').insert({channel_id:channel,name:name.trim(),price:Math.round(Number(price)*100),stock:Number(stock),active:true});if(insertError)throw insertError;setName('');setPrice('');setStock('');await load();}catch{setError(t('phase3.errors.generic'));}};
  return <PageFrame eyebrow={t('phase3.store.eyebrow')} title={t('phase3.store.creatorTitle')} intro={t('phase3.store.creatorIntro')}><Phase3Error error={error}/><Ficha><form onSubmit={create} className="grid gap-4 md:grid-cols-2"><select value={channel} onChange={e=>setChannel(e.target.value)} className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50">{channels.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><input value={name} onChange={e=>setName(e.target.value)} required className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><input value={price} onChange={e=>setPrice(e.target.value)} required inputMode="decimal" className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><input value={stock} onChange={e=>setStock(e.target.value)} required inputMode="numeric" className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><Botao type="submit">{t('phase3.store.create')}</Botao></form></Ficha></PageFrame>;
}

export function CreatorLiveStudioPage() {
  const { t }=useTranslation(); const [channels,setChannels]=useState<Channel[]>([]); const [channel,setChannel]=useState(''); const [items,setItems]=useState<LiveSession[]>([]); const [title,setTitle]=useState(''); const [mode,setMode]=useState<'free'|'paid'>('free'); const [price,setPrice]=useState(''); const [scheduledAt,setScheduledAt]=useState(''); const [error,setError]=useState<string|null>(null);
  const load=async()=>{if(!supabase)return;try{setItems(await phase3Rows<LiveSession>(supabase,'live_sessions','id,channel_id,title,mode,price,status'));}catch{setError(t('phase3.errors.generic'));}};
  useEffect(()=>{if(!supabase)return;void Promise.all([phase3Rows<Channel>(supabase,'channels','id,display_name'),load()]).then(([c])=>{setChannels(c);if(c[0])setChannel(c[0].id);});},[]);
  const create=async(e:FormEvent)=>{e.preventDefault();try{await phase3Rpc('create_live_session',{_channel:channel,_mode:mode,_title:title,_description:null,_price:mode==='paid'?Math.round(Number(price)*100):null,_scheduled_at:scheduledAt?new Date(scheduledAt).toISOString():null});setTitle('');setPrice('');setScheduledAt('');await load();}catch{setError(t('phase3.errors.generic'));}};
  return <PageFrame eyebrow={t('phase3.live.eyebrow')} title={t('phase3.live.creatorTitle')} intro={t('phase3.live.creatorIntro')}><Phase3Error error={error}/><Ficha><form onSubmit={create} className="grid gap-4 md:grid-cols-2"><select value={channel} onChange={e=>setChannel(e.target.value)} className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50">{channels.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><input value={title} onChange={e=>setTitle(e.target.value)} required className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><select value={mode} onChange={e=>setMode(e.target.value as 'free'|'paid')} className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"><option value="free">{t('phase3.live.mode.free')}</option><option value="paid">{t('phase3.live.mode.paid')}</option></select>{mode==='paid'?<input value={price} onChange={e=>setPrice(e.target.value)} required inputMode="decimal" className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/>:null}<input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><Botao type="submit">{t('phase3.live.create')}</Botao></form></Ficha></PageFrame>;
}

export function CreatorAnalyticsAdvancedPage() {
  const { t }=useTranslation(); const [dash,setDash]=useState<Dashboard|null>(null); const [daily,setDaily]=useState<DailyAnalytics[]>([]); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{void phase3Rpc<Dashboard>('get_creator_dashboard').then(setDash).catch(()=>setError(t('phase3.errors.generic')));if(supabase)void phase3Rows<DailyAnalytics>(supabase,'creator_analytics_daily','day,views,unique_viewers,messages,sales,gross_amount,tips,live_minutes').then(setDaily).catch(()=>setError(t('phase3.errors.generic')));},[t]);
  return <PageFrame eyebrow={t('phase3.analytics.eyebrow')} title={t('phase3.analytics.title')} intro={t('phase3.analytics.intro')}><Phase3Error error={error}/>{dash?<div className="grid gap-4 md:grid-cols-3"><Ficha><p className="text-xs uppercase text-bone-500">{t('phase3.analytics.metric.pending')}</p><p className="mt-3 font-display text-3xl text-bone-50">{formatMznFromCents(dash.pending)}</p></Ficha><Ficha><p className="text-xs uppercase text-bone-500">{t('phase3.analytics.metric.available')}</p><p className="mt-3 font-display text-3xl text-bone-50">{formatMznFromCents(dash.available)}</p></Ficha><Ficha><p className="text-xs uppercase text-bone-500">{t('phase3.analytics.metric.followers')}</p><p className="mt-3 font-display text-3xl text-bone-50">{dash.followers}</p></Ficha></div>:null}<div className="mt-6 grid gap-3">{daily.map(day=><Ficha key={day.day}><div className="flex justify-between"><span className="text-bone-50">{day.day}</span><span className="text-sm text-bone-400">{day.views} {t('phase3.analytics.views')}</span></div><p className="mt-2 text-sm text-bone-400">{t('phase3.analytics.gross')}: {formatMznFromCents(day.gross_amount)}</p></Ficha>)}</div></PageFrame>;
}

export function CreatorFansAdvancedPage() {
  const { t }=useTranslation(); const [error,setError]=useState<string|null>(null); const [notes,setNotes]=useState<{id:string;fan_id:string;tag:string|null;note:string}[]>([]);
  useEffect(()=>{if(!supabase)return;void phase3Rows(supabase,'fan_notes','id,fan_id,tag,note').then(setNotes).catch(()=>setError(t('phase3.errors.generic')));},[t]);
  return <PageFrame eyebrow={t('phase3.fans.eyebrow')} title={t('phase3.fans.title')} intro={t('phase3.fans.intro')}><Phase3Error error={error}/><div className="grid gap-3">{notes.map(note=><Ficha key={note.id}><p className="text-bone-50">{note.tag??t('phase3.fans.untagged')}</p><p className="mt-2 text-sm text-bone-400">{note.note}</p></Ficha>)}</div>{!notes.length&&!error?<EstadoVazio title={t('phase3.fans.emptyTitle')} body={t('phase3.fans.emptyBody')}/>:null}</PageFrame>;
}

export function CreatorGoalsPage() {
  const { t }=useTranslation(); const [channels,setChannels]=useState<Channel[]>([]); const [channel,setChannel]=useState(''); const [name,setName]=useState(''); const [target,setTarget]=useState(''); const [starts,setStarts]=useState(''); const [ends,setEnds]=useState(''); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!supabase)return;void phase3Rows<Channel>(supabase,'channels','id,display_name').then(rows=>{setChannels(rows);if(rows[0])setChannel(rows[0].id);}).catch(()=>setError(t('phase3.errors.generic')));},[t]);
  const create=async(e:FormEvent)=>{e.preventDefault();try{if(!supabase)throw new Error();const {error:insertError}=await supabase.from('creator_goals').insert({channel_id:channel,name:name.trim(),target_amount:Math.round(Number(target)*100),starts_at:new Date(starts).toISOString(),ends_at:new Date(ends).toISOString(),status:'active'});if(insertError)throw insertError;setName('');setTarget('');setStarts('');setEnds('');}catch{setError(t('phase3.errors.generic'));}};
  return <PageFrame eyebrow={t('phase3.goals.eyebrow')} title={t('phase3.goals.title')} intro={t('phase3.goals.intro')}><Phase3Error error={error}/><Ficha><form onSubmit={create} className="grid gap-4 md:grid-cols-2"><select value={channel} onChange={e=>setChannel(e.target.value)} className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50">{channels.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><input value={name} onChange={e=>setName(e.target.value)} required className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><input value={target} onChange={e=>setTarget(e.target.value)} required inputMode="decimal" className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><input type="datetime-local" value={starts} onChange={e=>setStarts(e.target.value)} required className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><input type="datetime-local" value={ends} onChange={e=>setEnds(e.target.value)} required className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><Botao type="submit">{t('phase3.goals.create')}</Botao></form></Ficha></PageFrame>;
}

export function CreatorReferralPage() {
  const { t }=useTranslation(); const [error,setError]=useState<string|null>(null); const [code,setCode]=useState(''); const [redeem,setRedeem]=useState('');
  const create=async(e:FormEvent)=>{e.preventDefault();try{await phase3Rpc('create_referral_code',{_code:code});setCode('');}catch{setError(t('phase3.errors.generic'));}};
  const activate=async(e:FormEvent)=>{e.preventDefault();try{await phase3Rpc('redeem_referral',{_code:redeem});setRedeem('');}catch{setError(t('phase3.errors.generic'));}};
  return <PageFrame eyebrow={t('phase3.referral.eyebrow')} title={t('phase3.referral.title')} intro={t('phase3.referral.intro')}><Phase3Error error={error}/><div className="grid gap-4 md:grid-cols-2"><Ficha><form onSubmit={create} className="space-y-3"><input value={code} onChange={e=>setCode(e.target.value)} required className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><Botao type="submit">{t('phase3.referral.createButton')}</Botao></form></Ficha><Ficha><form onSubmit={activate} className="space-y-3"><input value={redeem} onChange={e=>setRedeem(e.target.value)} required className="min-h-11 w-full rounded-md bg-ink-900 px-3 text-bone-50"/><Botao type="submit">{t('phase3.referral.redeemButton')}</Botao></form></Ficha></div></PageFrame>;
}

export function CreatorAutoRepliesPage() {
  const { t }=useTranslation(); const [channels,setChannels]=useState<Channel[]>([]); const [channel,setChannel]=useState(''); const [trigger,setTrigger]=useState(''); const [reply,setReply]=useState(''); const [items,setItems]=useState<{id:string;trigger:string;reply:string}[]>([]); const [error,setError]=useState<string|null>(null);
  const load=async()=>{if(!supabase)return;try{setItems(await phase3Rows(supabase,'auto_replies','id,trigger,reply'));}catch{setError(t('phase3.errors.generic'));}};
  useEffect(()=>{if(!supabase)return;void Promise.all([phase3Rows<Channel>(supabase,'channels','id,display_name'),load()]).then(([rows])=>{setChannels(rows);if(rows[0])setChannel(rows[0].id);});},[]);
  const create=async(e:FormEvent)=>{e.preventDefault();try{if(!supabase)throw new Error();const {error:insertError}=await supabase.from('auto_replies').insert({channel_id:channel,trigger:trigger.trim(),reply:reply.trim(),enabled:true});if(insertError)throw insertError;setTrigger('');setReply('');await load();}catch{setError(t('phase3.errors.generic'));}};
  return <PageFrame eyebrow={t('phase3.autoReplies.eyebrow')} title={t('phase3.autoReplies.title')} intro={t('phase3.autoReplies.intro')}><Phase3Error error={error}/><Ficha><form onSubmit={create} className="grid gap-4 md:grid-cols-3"><select value={channel} onChange={e=>setChannel(e.target.value)} className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50">{channels.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select><input value={trigger} onChange={e=>setTrigger(e.target.value)} required className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><input value={reply} onChange={e=>setReply(e.target.value)} required className="min-h-11 rounded-md bg-ink-900 px-3 text-bone-50"/><Botao type="submit">{t('phase3.autoReplies.create')}</Botao></form></Ficha><div className="mt-5 grid gap-3">{items.map(item=><Ficha key={item.id}><p className="text-bone-50">{item.trigger}</p><p className="text-sm text-bone-400">{item.reply}</p></Ficha>)}</div></PageFrame>;
}

export function ClientRewardsPage() {
  const { t }=useTranslation(); const [data,setData]=useState<Loyalty|null>(null); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{void phase3Rpc<Loyalty>('get_loyalty_status').then(setData).catch(()=>setError(t('phase3.errors.generic')));},[t]);
  return <PageFrame eyebrow={t('phase3.rewards.eyebrow')} title={t('phase3.rewards.title')} intro={t('phase3.rewards.intro')}><Phase3Error error={error}/>{data?<div className="grid gap-4 md:grid-cols-4">{[['points',data.points],['lifetime',data.lifetime_points],['level',data.level??t('phase3.rewards.unconfigured')],['streak',data.current_streak]].map(([key,value])=><Ficha key={String(key)}><p className="text-xs uppercase text-bone-500">{t(\`phase3.rewards.metric.\${String(key)}\`)}</p><p className="mt-3 font-display text-3xl text-bone-50">{String(value)}</p></Ficha>)}</div>:null}</PageFrame>;
}