import { useEffect, useMemo, useState } from 'react';
import { DeviceMobile, ShieldCheck, SignOut, LockKey, CheckCircle, XCircle } from '@phosphor-icons/react';
import { useTranslation } from 'react-i18next';
import { useAuth } from '@/app/session';
import { requireSupabase } from '@/lib/supabase';
import { Ficha } from '@/design/Ficha';
import { Botao } from '@/design/Botao';

type Overview={aal:string;mfa_enrolled:boolean;session_id:string|null;account_status:string;kyc_status:string|null;self_excluded_until:string|null;required_terms_accepted:boolean;required_privacy_accepted:boolean};
type SessionRow={session_id:string;device_label:string|null;first_seen_at:string;last_seen_at:string;revoked_at:string|null;trusted:boolean;current_session:boolean};
type DeviceRow={id:string;device_label:string;created_at:string;last_seen_at:string;revoked_at:string|null};

export function SecuritySettingsPage() {
 const {t}=useTranslation(); const {user}=useAuth();
 const [overview,setOverview]=useState<Overview|null>(null); const [sessions,setSessions]=useState<SessionRow[]>([]); const [devices,setDevices]=useState<DeviceRow[]>([]);
 const [mfaCode,setMfaCode]=useState(''); const [factorId,setFactorId]=useState<string|null>(null); const [qr,setQr]=useState<string|null>(null); const [secret,setSecret]=useState<string|null>(null);
 const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(false);

 const sb=useMemo(()=>requireSupabase(),[]);
 const load=async()=>{ if(!user)return; const [ov,se,dev,mf]=await Promise.all([sb.rpc('get_security_overview'),sb.rpc('list_current_sessions'),sb.from('trusted_devices').select('id,device_label,created_at,last_seen_at,revoked_at').order('last_seen_at',{ascending:false}),sb.auth.mfa.listFactors()]); if(!ov.error)setOverview(ov.data as Overview); if(!se.error)setSessions((se.data??[]) as SessionRow[]); if(!dev.error)setDevices((dev.data??[]) as DeviceRow[]); if(!mf.error){const verified=mf.data.totp.find((f)=>f.status==='verified'); if(verified)setFactorId(verified.id);}};
 useEffect(()=>{void load();},[user]);

 const enroll=async()=>{setError(null);setLoading(true);const result=await sb.auth.mfa.enroll({factorType:'totp',friendlyName:'Prively'});setLoading(false);if(result.error){setError(result.error.message);return;}setFactorId(result.data.id);setQr(result.data.totp.qr_code);setSecret(result.data.totp.secret);};
 const verify=async()=>{if(!factorId)return;setError(null);setLoading(true);const challenge=await sb.auth.mfa.challenge({factorId});if(challenge.error){setLoading(false);setError(challenge.error.message);return;}setChallengeId(challenge.data.id);const result=await sb.auth.mfa.verify({factorId,challengeId:challenge.data.id,code:mfaCode});setLoading(false);if(result.error){setError(result.error.message);return;}await sb.auth.refreshSession();setQr(null);setSecret(null);setChallengeId(null);setMfaCode('');await load();};
 const signOutOthers=async()=>{setLoading(true);const result=await sb.auth.signOut({scope:'others'});setLoading(false);if(result.error)setError(result.error.message);else await load();};
 const trust=async()=>{setLoading(true);const result=await sb.rpc('trust_current_device',{_device_label:navigator.userAgent.slice(0,80)});setLoading(false);if(result.error)setError(result.error.message);else await load();};
 const revoke=async(id:string)=>{setLoading(true);const result=await sb.rpc('revoke_trusted_device',{_device_id:id});setLoading(false);if(result.error)setError(result.error.message);else await load();};

 return <section className="mx-auto max-w-5xl space-y-8">
  <div><p className="flex items-center gap-2 text-sm text-bone-500"><ShieldCheck size={19} weight="duotone"/>{t('security.eyebrow')}</p><h1 className="mt-4 font-display text-6xl leading-none text-bone-50">{t('security.title')}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-bone-300">{t('security.body')}</p></div>
  {error?<p role="alert" className="rounded-md border border-danger/35 bg-danger/5 p-4 text-sm text-bone-50">{error}</p>:null}
  {overview?<div className="grid gap-4 md:grid-cols-3"><Ficha className="p-5"><p className="text-xs uppercase tracking-[.16em] text-bone-500">{t('security.assurance')}</p><p className="mt-3 text-2xl font-semibold text-bone-50">{overview.aal}</p></Ficha><Ficha className="p-5"><p className="text-xs uppercase tracking-[.16em] text-bone-500">{t('security.mfa')}</p><p className="mt-3 flex items-center gap-2 text-2xl font-semibold text-bone-50">{overview.mfa_enrolled?<CheckCircle className="text-ok"/>:<XCircle className="text-bone-500"/>}{overview.mfa_enrolled?t('security.enabled'):t('security.notEnabled')}</p></Ficha><Ficha className="p-5"><p className="text-xs uppercase tracking-[.16em] text-bone-500">{t('security.account')}</p><p className="mt-3 text-2xl font-semibold text-bone-50">{overview.account_status}</p></Ficha></div>:null}
  <Ficha variant="focus" className="p-6 md:p-8"><div className="flex items-start justify-between gap-5"><div><h2 className="text-xl font-semibold text-bone-50">{t('security.mfaTitle')}</h2><p className="mt-2 text-sm leading-6 text-bone-300">{t('security.mfaBody')}</p></div><ShieldCheck size={24} className="text-crimson-400"/></div>{!factorId&&!qr?<Botao className="mt-6" onClick={()=>void enroll()} loading={loading}>{t('security.enableMfa')}</Botao>:null}{qr?<div className="mt-6 grid gap-6 md:grid-cols-[180px_1fr]"><img src={qr} alt={t('security.qrAlt')} className="h-44 w-44 rounded bg-white p-2"/><div><p className="text-sm text-bone-300">{t('security.secret')}: <code className="text-bone-50">{secret}</code></p><label className="mt-5 block"><span className="mb-2 block text-sm text-bone-300">{t('security.code')}</span><input value={mfaCode} onChange={(e)=>setMfaCode(e.target.value.replace(/\D/g,'').slice(0,8))} inputMode="numeric" className="min-h-12 w-full rounded-md border border-input bg-ink-850 px-3 text-bone-50 outline-none"/></label><Botao className="mt-4" onClick={()=>void verify()} loading={loading}>{t('security.verify')}</Botao></div></div>:factorId&&!overview?.mfa_enrolled?<Botao className="mt-6" onClick={()=>void enroll()} loading={loading}>{t('security.reconfigureMfa')}</Botao>:null}</Ficha>
  <div className="grid gap-6 lg:grid-cols-2"><Ficha className="p-6"><div className="flex items-center gap-3"><DeviceMobile size={22} className="text-crimson-400"/><h2 className="text-xl font-semibold text-bone-50">{t('security.sessions')}</h2></div><div className="mt-5 space-y-3">{sessions.length?sessions.map((session)=><div key={session.session_id} className="rounded-md border border-bone-50/8 bg-ink-850 p-4"><div className="flex items-center justify-between gap-4"><div><p className="font-medium text-bone-50">{session.device_label||t('security.unknownDevice')}</p><p className="mt-1 text-xs text-bone-500">{session.current_session?t('security.current'):t('security.sessionActive')}</p></div>{session.trusted?<span className="text-xs text-ok">{t('security.trusted')}</span>:null}</div></div>):<p className="text-sm text-bone-500">{t('security.noSessions')}</p>}</div><Botao variant="outline" className="mt-5" onClick={()=>void signOutOthers()} loading={loading}><SignOut size={18}/>{t('security.signOutOthers')}</Botao></Ficha>
  <Ficha className="p-6"><div className="flex items-center gap-3"><LockKey size={22} className="text-crimson-400"/><h2 className="text-xl font-semibold text-bone-50">{t('security.devices')}</h2></div>{overview?.aal==='aal2'?<Botao variant="outline" className="mt-5" onClick={()=>void trust()} loading={loading}>{t('security.trustCurrent')}</Botao>:<p className="mt-5 text-sm text-bone-500">{t('security.trustRequiresMfa')}</p>}<div className="mt-5 space-y-3">{devices.map((device)=><div key={device.id} className="flex items-center justify-between gap-4 rounded-md border border-bone-50/8 bg-ink-850 p-4"><div><p className="text-sm text-bone-50">{device.device_label}</p><p className="mt-1 text-xs text-bone-500">{device.revoked_at?t('security.revoked'):t('security.trusted')}</p></div>{!device.revoked_at?<Botao variant="ghost" onClick={()=>void revoke(device.id)} loading={loading}>{t('security.revoke')}</Botao>:null}</div>)}</div></Ficha></div>
 </section>;
}
