export const featureFlags = {
  designSystem: true,
  ageGate: true,
  auth: true,
  phase2Experience: true,
  phase3Monetization: false,
  phase6Financials: true,
  creatorStudio: false,
  wallet: true,
  payments: true,
  messaging: true,
  push: false,
  translation: false,
  live: false,
  meetings: true,
  moderation: true,
  aiModeration: false,
  safetyAlerts: false,
  dmca: true,
  agency: false,
  phase9Business: true,
  customRequests: true,
  auctions: true,
  bundles: true,
  promotions: true,
  gifts: true,
  store: true,
  giveaways: true,
  loyalty: true,
  fanRanking: true,
  creatorAnalytics: true,
  fanCrm: true,
  creatorGoals: true,
  referral: false,
  premiumFeatures: true,
  featuredCreators: true,
  recommendations: true,
  aiResponseAssistant: false,
  autoCaptions: false,
  faceBlur: false,
  advancedMediaProcessing: false
} as const;

export function isFeatureEnabled(name: keyof typeof featureFlags): boolean {
  return featureFlags[name];
}
