export const homeCopy = {
  'pt-MZ': {
    curtainOpen: 'Fechar a cortina',
    curtainClosed: 'Abrir a cortina',
    sectionEyebrow: 'O Privê por dentro',
    sectionTitle: 'Um só espaço para conteúdo, ligação e controlo.',
    sectionBody: 'A Prively junta conteúdo por assinatura, rede social e carteira digital num espaço pensado para adultos.',
    pillars: [
      { title: 'Conteúdo', body: 'Assinaturas, compras avulso, pedidos e outras formas de apoiar criadoras.' },
      { title: 'Rede social', body: 'Perfis, seguir, comentários, mensagens, transmissões ao vivo e descoberta.' },
      { title: 'Carteira', body: 'Saldo em meticais para carregar e gastar dentro da plataforma.' },
    ],
    privacyEyebrow: 'Discrição a sério',
    privacyTitle: 'O teu perfil não precisa de contar a tua vida.',
    privacyBody: 'O cliente usa um pseudónimo. As notificações podem ser neutras. O modo discreto e o PIN ajudam a proteger o acesso no dia-a-dia.',
    creatorEyebrow: 'Para criadoras',
    creatorTitle: 'O teu conteúdo. As tuas regras.',
    creatorBody: 'A criadora decide o que publica, o que é grátis ou pago, os preços e quem pode ver. Também acompanha os seus ganhos e relações com fãs.',
    safetyEyebrow: 'Confiança',
    safetyTitle: 'Regras claras antes de qualquer acesso.',
    safetyItems: ['18+ e verificação de identidade', 'Consentimento em cada publicação', 'Denúncia, bloqueio e moderação', 'Dinheiro e permissões decididos no servidor'],
    journeyEyebrow: 'Como começa',
    journeyTitle: 'Quatro passos. Sem atalhos.',
    journey: [
      { no: '01', title: 'Confirma a idade', body: 'A porta de entrada começa com a confirmação de que tens 18 anos ou mais.' },
      { no: '02', title: 'Cria a tua conta', body: 'Email, palavra-passe e um pseudónimo para a tua identidade social.' },
      { no: '03', title: 'Verifica a identidade', body: 'Documento e selfie. Sem verificação, não há acesso a conteúdo adulto nem gastos.' },
      { no: '04', title: 'Entra no Privê', body: 'Depois da aprovação, o cliente continua anónimo para o resto da plataforma.' },
    ],
    socialNote: 'A agenda social existe como ferramenta de disponibilidade. A Prively não cobra por encontros, não fixa preços de actos sexuais e não intermedeia serviços sexuais.',
    finalEyebrow: 'Duas portas',
    finalTitle: 'Escolhe como queres entrar.',
    finalBody: 'A experiência pública começa sem conteúdo explícito. O acesso ao conteúdo adulto só acontece depois dos controlos previstos pela plataforma.',
  },
  en: {
    curtainOpen: 'Close the curtain',
    curtainClosed: 'Open the curtain',
    sectionEyebrow: 'Inside the Privê',
    sectionTitle: 'One space for content, connection and control.',
    sectionBody: 'Prively brings subscription content, social features and a digital wallet into one adult-only space.',
    pillars: [
      { title: 'Content', body: 'Subscriptions, one-off purchases, requests and other ways to support creators.' },
      { title: 'Social', body: 'Profiles, following, comments, messages, live streams and discovery.' },
      { title: 'Wallet', body: 'A metical balance to top up and spend inside the platform.' },
    ],
    privacyEyebrow: 'Privacy that shows up',
    privacyTitle: 'Your profile does not need to tell your whole story.',
    privacyBody: 'Clients use a pseudonym. Notifications can stay neutral. Discreet mode and a PIN help protect access day to day.',
    creatorEyebrow: 'For creators',
    creatorTitle: 'Your content. Your rules.',
    creatorBody: 'Creators decide what they publish, what is free or paid, the prices and who can see it. They can also track earnings and fan relationships.',
    safetyEyebrow: 'Trust',
    safetyTitle: 'Clear rules before any access.',
    safetyItems: ['18+ and identity verification', 'Consent on every publication', 'Reporting, blocking and moderation', 'Money and permissions enforced on the server'],
    journeyEyebrow: 'How it starts',
    journeyTitle: 'Four steps. No shortcuts.',
    journey: [
      { no: '01', title: 'Confirm your age', body: 'The entrance starts by confirming that you are 18 or older.' },
      { no: '02', title: 'Create your account', body: 'Email, password and a pseudonym for your social identity.' },
      { no: '03', title: 'Verify your identity', body: 'Document and selfie. Without verification, there is no access to adult content or spending.' },
      { no: '04', title: 'Enter the Privê', body: 'After approval, the client remains anonymous to the rest of the platform.' },
    ],
    socialNote: 'The social agenda is a free availability tool. Prively does not charge for meetings, set prices for sexual acts or broker sexual services.',
    finalEyebrow: 'Two doors',
    finalTitle: 'Choose how you want to enter.',
    finalBody: 'The public experience starts without explicit content. Adult content is only available after the platform checks required by Prively.',
  },
  fr: {
    curtainOpen: 'Fermer le rideau',
    curtainClosed: 'Ouvrir le rideau',
    sectionEyebrow: 'Dans le Privê',
    sectionTitle: 'Un seul espace pour contenu, lien et contrôle.',
    sectionBody: 'Prively réunit contenu par abonnement, fonctions sociales et portefeuille numérique dans un espace réservé aux adultes.',
    pillars: [
      { title: 'Contenu', body: 'Abonnements, achats à l’unité, demandes et autres façons de soutenir les créatrices.' },
      { title: 'Réseau social', body: 'Profils, abonnements, commentaires, messages, directs et découverte.' },
      { title: 'Portefeuille', body: 'Un solde en meticais pour recharger et dépenser dans la plateforme.' },
    ],
    privacyEyebrow: 'La discrétion, pour de vrai',
    privacyTitle: 'Ton profil n’a pas besoin de raconter toute ta vie.',
    privacyBody: 'Le client utilise un pseudonyme. Les notifications peuvent rester neutres. Le mode discret et le PIN protègent l’accès au quotidien.',
    creatorEyebrow: 'Pour les créatrices',
    creatorTitle: 'Ton contenu. Tes règles.',
    creatorBody: 'La créatrice décide ce qu’elle publie, ce qui est gratuit ou payant, les prix et qui peut voir. Elle suit aussi ses revenus et ses relations avec ses fans.',
    safetyEyebrow: 'Confiance',
    safetyTitle: 'Des règles claires avant tout accès.',
    safetyItems: ['18+ et vérification d’identité', 'Consentement pour chaque publication', 'Signalement, blocage et modération', 'Argent et permissions appliqués côté serveur'],
    journeyEyebrow: 'Comment ça commence',
    journeyTitle: 'Quatre étapes. Sans raccourci.',
    journey: [
      { no: '01', title: 'Confirme ton âge', body: 'L’entrée commence par la confirmation que tu as 18 ans ou plus.' },
      { no: '02', title: 'Crée ton compte', body: 'Email, mot de passe et pseudonyme pour ton identité sociale.' },
      { no: '03', title: 'Vérifie ton identité', body: 'Document et selfie. Sans vérification, aucun accès au contenu adulte ni aux dépenses.' },
      { no: '04', title: 'Entre dans le Privê', body: 'Après validation, le client reste anonyme pour le reste de la plateforme.' },
    ],
    socialNote: 'L’agenda social est un outil gratuit de disponibilité. Prively ne facture pas les rencontres, ne fixe pas de prix pour des actes sexuels et n’intermédie pas de services sexuels.',
    finalEyebrow: 'Deux portes',
    finalTitle: 'Choisis comment tu veux entrer.',
    finalBody: 'L’expérience publique commence sans contenu explicite. Le contenu adulte n’est accessible qu’après les contrôles prévus par Prively.',
  },
} as const;
