-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928225222 (phase7_live_room_contract).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
