-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928222219 (phase6_payout_encryption_qualification).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
