-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928142045 (phase4_security_rls_helper_allowlist).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
