-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928220911 (phase5_retention_setting_contract).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
