-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928215639 (phase5_processing_access_audit).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
