-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928145353 (phase5_fix_legal_acceptance_ambiguity).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
