-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928142655 (phase4_fix_self_exclusion_function).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
