-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928221926 (phase6_payment_worker_grants).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
