-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928215920 (phase5_internal_worker_dispatch_v2).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
