-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928134747 (tighten_public_function_execute).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
