-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928151643 (phase5_processing_upload_hardening).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
