-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928215559 (phase5_compliance_archive_and_server_hash).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
