-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928143713 (phase5_media_visibility_gate).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
