-- Phase 4 ledger foundation placeholder
--
-- The canonical ledger type, ledger_entries and balances already exist from
-- the earlier production Phase 3 migration. The next migration performs the
-- remaining Phase 4 hardening idempotently on top of that schema.
--
-- This placeholder is intentionally DDL-free so clean resets and production
-- pushes do not recreate the existing ledger type or tables.
