-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928222956 (phase6_financial_rpc_grants_hardening).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
