-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928225754 (phase7_realtime_topic_split).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
