-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928131234 (admin_authorization_grants).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
