-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928142209 (phase4_function_public_grant_hardening).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
