-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928222336 (phase6_finance_reconciliation_rpc).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
