-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928220411 (phase5_safe_locked_preview).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
