-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928222919 (phase6_subscription_idempotency).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
