-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928145123 (phase5_security_advisor_hardening).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
