-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928144001 (phase5_media_processing_queue).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
