-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928225031 (phase7_social_realtime_communication).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
