-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928141743 (phase4_security_definer_execute_allowlist).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
