-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928222151 (phase6_ledger_invariants).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
