-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928225635 (phase7_rls_block_oracle_hardening).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
