-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928220713 (phase5_finalize_returns_job_ids).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
