-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928230051 (phase7_security_lint_cleanup).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
