-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928134730 (lock_public_security_definers).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
