-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928222548 (phase6_fx_refresh_worker).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
