-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928141052 (phase4_admin_security_queries).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
