-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928144508 (phase5_blurhash_and_media_size_hardening).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
