-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928140907 (phase4_identity_access_security_policies).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
