-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928142128 (phase4_revoke_anon_security_definers).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
