-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928152208 (phase5_remove_admin_storage_read_bypass).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
