-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928225822 (phase7_push_delivery_contract).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
