-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928152347 (phase5_archive_publication_events).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
