-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928134155 (normalize_test_auth_users_v2).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
