-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928220157 (phase5_disable_unverified_dispatch).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
