-- Supabase migration history reconciliation marker.
-- Remote project already records 20260928142929 (phase4_require_aal2_for_kyc_admin_action).
-- The repository carries the consolidated/local implementation under later migration filenames.
-- This marker intentionally performs no schema or data mutation.
